### ISSUE TITLE
Add Filter for identifier in GET volume API

### ISSUE THREAD

**Issue by NajmudheenCT** [opensds/opensds#1083]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
NBP plugin (VMWARe NGC and VRO ) need to query volume by ading filter unique_identifier (wwn)
**What you expected to happen**:
GET /block/volumes?unique_id=<wwn/eui> should be supported
**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
As of now unique identifier is implemnted only for lvm backend
**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
It's Fixed. Confirmed by Naju. The PR for this fix are #1099 and #1142
