### ISSUE TITLE
Installer script in devsds does not work if etcd is already installed with a different version

### ISSUE THREAD

**Issue by joseph-v** [opensds/opensds#1090]
OpenSDS devsds installer do not consider version of etcd if etcd is already installed.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When trying to install opensds using 'install/devsds/install.sh', in a system with already installed etcd, installer failed.

**What you expected to happen**:
Installer should be using a consistent version of etcd as configured.

**How to reproduce it (as minimally and precisely as possible)**:
Install latest etcd 3.4 in the system and try to run installer script.

**Comment by PravinRanjan10** [comment]
It's Fixed. The PR for fix is #1091
