### ISSUE TITLE
Telemetry : Update swagger for metrics API

### ISSUE THREAD

**Issue by NajmudheenCT** [opensds/opensds#1093]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In V0.6.2 release of hotpot , Metric API requests do not execute as the controller enabled swagger validation. metrics APIs do not have swaager reference now.
**What you expected to happen**:
All metrics APIs shuld work as in Capri release. Need to have swaager for metrics APIS
**How to reproduce it (as minimally and precisely as possible)**:
clone v0.6.2 tag , install opensds with telemtetry. go to dashboard/telemetry . Tab to open Grafana and Alert Manager will not come up.

**Anything else we need to know?**:
NA
**Environment**:
- Hotpot(release/branch) version: v0.6.2
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
Fixed!! Confirmed by Naju. Fix is here #1096
