### ISSUE TITLE
Swagger file validation issues for fileshare acl

### ISSUE THREAD

**Issue by sushanthakumar** [opensds/opensds#1100]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When we create fileshare spec with swagger validation enabled, below 2 issues are faced
1) tenantId is treated as mandatory which is not correct
2) accessCapability is treated as string which should be array of string

![image](https://user-images.githubusercontent.com/30930862/70204336-268ac680-1746-11ea-83a4-3bba81d02976.png)

Swagger files snapshots:

![image](https://user-images.githubusercontent.com/30930862/70204371-4a4e0c80-1746-11ea-96a7-88f5938ac97b.png)

![image](https://user-images.githubusercontent.com/30930862/70204399-618cfa00-1746-11ea-9464-f5e053c4272a.png)

**What you expected to happen**:
Swagger file updated needed for
1) Removing tenantId from "required" list
2) Updating accessCapability type to array of strings

**Probable fix **which need to be checked further**** 

![image](https://user-images.githubusercontent.com/30930862/70204565-14f5ee80-1747-11ea-8aa2-1661a71277e6.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
Fixed, Closing now!!!
