### ISSUE TITLE
Get "ERROR: 500 Internal Server Error" when creating volume without specifying profile

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/opensds#1124]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
When I want to create a volume without specifying profile, I get an error "500 Internal Server Error", but as a user I have no idea what is wrong.
```
root@node01:~/gopath/src/github.com/opensds/opensds (development) # osdsctl profile list
+--------------------------------------+---------+----------------+-------------+
| Id                                   | Name    | Description    | StorageType |
+--------------------------------------+---------+----------------+-------------+
| f832df81-883c-4149-a167-10c8e59fbc01 | default | default policy | block       |
+--------------------------------------+---------+----------------+-------------+
root@node01:~/gopath/src/github.com/opensds/opensds (development) # osdsctl volume create 1 --name=test-001
ERROR: 500 Internal Server Error
root@node01:~/gopath/src/github.com/opensds/opensds (development)
```
**What you expected to happen**:
When I want to create a volume without specifying profile, I can create it successfully with default profile, or I can know what is wrong.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: latest
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
I have verified, It's working fine. Now closing this issue.
Issue has been fixed though this PR #1125 
root@root1-Latitude-E7450:~/opensds-installer/ansible# osdsctl volume create 1 --name="vol5"
ERROR: get default profile failed: can't find profile(name: default_block, storageType:block)
