### ISSUE TITLE
Modify Host information is not updating OSType

### ISSUE THREAD

**Issue by anvithks** [opensds/opensds#1138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I tried to modify an existing host and changed the OS Type from ESXi to Windows. There was no error and the modify api returned success. 
**What you expected to happen**:
The Host information should have been modified and the OS Type should be displayed as Windows.
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Host with OS Type selected as Linux.
2. After successful creation, click on Modify Host.
3. Change the OS Type to anything else for ex: Windows.
4. The modify function is successful ad The host list page is shown. 
5. Check the Host details.

**Anything else we need to know?**:
Create Host
![craete-page](https://user-images.githubusercontent.com/19162717/71166047-ed8b3f80-2277-11ea-8dd7-cc42f6b5aa29.png)
Create Host POST Request
![create-post-request](https://user-images.githubusercontent.com/19162717/71166067-f3812080-2277-11ea-8cd1-41996761d892.png)
Modify Host PUT Request
![modified-host-to-windows](https://user-images.githubusercontent.com/19162717/71166101-05fb5a00-2278-11ea-9549-86077a0384de.png)
Modify Host PUT Response
![response-to-modify](https://user-images.githubusercontent.com/19162717/71166144-17dcfd00-2278-11ea-985f-b34ba76c662c.png)
Host Details after Modify
![modified-host-to-windows-frontend](https://user-images.githubusercontent.com/19162717/71166169-25928280-2278-11ea-9d16-f51a0b7f3b69.png)

**Environment**:
- Hotpot(release/branch) version: v0.7.0
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): `Linux opensds-VirtualBox 4.15.0-72-generic #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by wisererik** [comment]
it's solved, will close it
