### ISSUE TITLE
Hotpot: Volume create is throwing syntax error if we give size in float value

### ISSUE THREAD

**Issue by PravinRanjan10** [opensds/opensds#1147]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

 Volume create is throwing syntax error if we give size in float value. And also not able to create volume.
ex:
/root/opensds# osdsctl volume create 1.5 --name="vol3" --debug 
DEBUG: 2019/12/24 21:19:02 volume.go:145: error parsing size 1.5: strconv.Atoi: parsing "1.5": invalid syntax

**What you expected to happen**:
It should throw correct error message. if float type is not allowd in size.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Actually LVM supports creating volume with float size value, so OSDS should also allow
