### ISSUE TITLE
The volume can not be deleted in OpenSDS if the volume doesn't exist on storage device

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/opensds#1181]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
If the volume actually do not exist on storage device, we can not delete it from OpenSDS

**What you expected to happen**:
If the volume actually do not exist on storage device, we should be able to delete it from OpenSDS

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a volume by OpenSDS
2. Delete the volume on the storage device
3. Delete the volume from OpenSDS

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: latest
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sushanthakumar** [comment]
Info: This issue was observed while using oceanstor driver

**Comment by ThisIsClark** [comment]
Fixed in PR #1183
