### ISSUE TITLE
Invalid log appears repeatedly

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/opensds#1186]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Improvement

**What happened**:
Invalid log appears repeatedly, should be deleted

**What you expected to happen**:
Invalid log should not appear

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by joseph-v** [comment]
LGTM

**Comment by ThisIsClark** [comment]
Fixed in PR #1188
