### ISSUE TITLE
[QIP] CLI for listing pool do not respect offset query parameter

### ISSUE THREAD

**Issue by joseph-v** [opensds/opensds#1201]
Command 'osdsctl pool list --limit=3 --offset=5', when run with 3 pools created, shows a pool in the output.

/kind bug

**What you expected to happen**:
osdsctl command should list zero pools when offset is larger than number of pools.

**How to reproduce it (as minimally and precisely as possible)**:
- Create 3 pools
- List these pools using, 'osdsctl pool list --limit=3 --offset=5'

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
LGTM
