### ISSUE TITLE
[QIP] CLI: Support pool flag for creating volume using specific pool

### ISSUE THREAD

**Issue by himanshuvar** [opensds/opensds#1208]
> /kind feature

**What happened**:
There is no flag support in **CLI** to provide which pool to select for creating the volume

**What you expected to happen**:
CLI should support pool flag

**How to reproduce it (as minimally and precisely as possible)**:
create volume on specific pool using CLI

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
![6](https://user-images.githubusercontent.com/8712951/73439278-67354380-4375-11ea-97d2-6c5efc6806ec.PNG)

**Comment by PravinRanjan10** [comment]
**Few more cases**
case1: there is no option to create volume using **groupId**(but in swagger there is parameters)
case2: there is no option to create volume using **replication**(but in swagger there is parameters)
case3: tried to create volume from snapshot, why it is asking size and name again(i know it's required parameters but we need to handle in some scenario)
