### ISSUE TITLE
Extend Volume

### ISSUE THREAD

**Issue by PengYiOfOpenSDS** [opensds/opensds#249]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
  In the current version, the OpenSDS doesn't support "Extend Volume".

**What you expected to happen**:
  Extends the size of a volume to a requested size, in gibibytes (GiB).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
  List of work items:
  1. Add an api (v1/{ProjectID}/ volumes/{VolumeID} /action).
  2. Add a cli command (osdsctl volume extend <id> <new size>).
  3. Implement extend volume in volume controller.
  4. Add logic in the selector to handle extend volume.
  5. Implement extend volume in drivers.
**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Since this issue has been solved, I suggest we keep it open for a while to see if any question remains.

**Comment by leonwanghui** [comment]
I think this issue can be closed now, please feel free to reopen it if anyone finds some bugs.
