### ISSUE TITLE
Helm Charts Support

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#254]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
[Helm](https://github.com/kubernetes/helm) is a popular package manager in Kubernetes. For easier deployment and operation, we should develop opensds charts to support helm.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by noelmcloughlin** [comment]
fyi, another agnostic packaging technology is [snapd](https://snapcraft.io/)

**Comment by leonwanghui** [comment]
@noelmcloughlin Looks like a cool installer tool! Can you draft an initial design proposal if you want to implement this feature? Thanks!

**Comment by leonwanghui** [comment]
@noelmcloughlin BTW, I will close this issue, please be free to set up a new one if you want to add `snapd` deployment.

**Comment by noelmcloughlin** [comment]
@leonwanghui Thanks. Raised Helm issue upstream.
 https://github.com/saltstack-formulas/packages-formula/issues/19
