### ISSUE TITLE
OpenSDS Kubernetes External Provisioner Design

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#29]
As we all know, Kubernetes provides a framework of storage for container orchestration layer.

When users create a PVC, Kubernetes controller will retrieve PV from backends through a "Provisioner" interface. But right now each backend has its own provisioner([nfs](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs), [efs](https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs), [cephfs](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs) and so on), and it's unbearable for vendors to maintain all provisoners if they want to support multiple backends.

To solve this problem, we launched a proposal #28 about designing a unified provisioner for different banckend storage types. Please be free to talk if you have any question : )

**Comment by hannibalhuang** [comment]
@johnmark @rchagam @stevenphtan @arvimal @kjellk @joehandzik

**Comment by leonwanghui** [comment]
closed
