### ISSUE TITLE
Is there any plan of security guarantee, such as https support,  sensitive data encryption, params check and so on.

### ISSUE THREAD

**Issue by prolen** [opensds/opensds#291]
Is there any plan of security guarantee, such as https support,  sensitive data encryption, params checking and so on.

**Comment by leonwanghui** [comment]
@prolen Thanks for your great question. Currently we do have supported https scheme and params check in api-server. For the rest part you mentioned, it would be all included in our future plan. If you are interested, any contribution is welcomed.

**Comment by leonwanghui** [comment]
Already resolved by #592  #598 #611
