### ISSUE TITLE
Add authentication and request filter in osdsctl and client package

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#294]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
According to keystone design (#289) and API request filter support (#284), opensds api-server has supported authentication and request filter features, but as for client and cli tool, these features also need to be supported.

**What you expected to happen**:
Add keystone authentication and api request filter support in cli and client tool.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
@xxwjj @lasshpanzer This issue is releated to PRs you have submitted, please take a look at it.

**Comment by xxwjj** [comment]
@leonwanghui okay,  got it. That's what I'm doing.

**Comment by leonwanghui** [comment]
@lasshpanzer Please take a look at this issue, because there are some issues when I test `osdsctl volume attachment list`.
