### ISSUE TITLE
lvm driver bug

### ISSUE THREAD

**Issue by xxwjj** [opensds/opensds#304]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind bug

**What happened**:

In opensds framework, we distinguish  volume by uuid, so the diffrent volumes can have the same name.
But the LVM driver does not support this feature,  it will return an error if you create two  volumes which have the same name.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
@xxwjj It's indeed a big issue to be solved, IMO one optional solution is to create a binding of `id:name` and pass it to volume name, which is much like what we did in ceph backend.
