### ISSUE TITLE
RFE: automatic deployment using Saltstack

### ISSUE THREAD

**Issue by noelmcloughlin** [opensds/opensds#320]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What you expected to happen**:
According to #60,  "_automatic deployment and installation become more and more important in a distributed system cluster. As a cloud-native storage system, opensds controller project MUST support (at least one of) automatic deployment_    

I'm interested in storage management, backup/restore, & SDS standards (i.e DMTF SMI-S, OpenLMI).

I want to work on automatic deployment of OpenSDS via **saltstack**.  
Do we have list of use case to satisfy?

**Anything else we need to know?**:

I'm thinking of publishing an opensds-formula [upstream](http://github.com/saltstack-formulas/), and integration instructions can go here.

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release): Linux/Darwin Containerized.
- Kernel (e.g. `uname -a`): any supported
- Install tools: saltstack
- Others:

**Comment by leonwanghui** [comment]
Hi, firstly thanks for your precious suggestion, and we are glad to see someone join and contribute in this community. Here I have some questions and I would appreciate if you can give some answers:

1. Can you give a simple introduction about yourself? (Who you are, which company do you work for)
2. What do you expect from this project? (ie. you want to utilize the standard, or make it a product)
3. Where do you prefer to do code development, under this project or in other communties?

Thanks!

**Comment by noelmcloughlin** [comment]
Hey @leonwanghui,  I working for Overstock.com based in Salt Lake City, but I'm here as hobbyist. As mentioned, I am interested in storage management, service availability, and systems automation. My primary skills are systems integration and good knowledge of Next Generation Operations Systems Support (OSS), Backup and Restore requirements and solutions.   I found OpenSDS today when reviewing  [Stor4NFV](https://wiki.opnfv.org/display/PROJ/Stor4NFV) and believe software-defined storage management and orchestration is somewhat neglected - so I'm interested in the concept.

I would like to start code development on opensds-formula for saltstack, to start building my competence in OpenSDS, and thereafter I would hope to be contributor to this community.

Thanks

**Comment by xing-yang** [comment]
@noelmcloughlin That's great!  Thanks for your interest in contributing to OpenSDS!  Let us know how it goes with the opensds-formula and if you have any questions.

**Comment by stmcginnis** [comment]
Welcome @noelmcloughlin!

Just a thought for everyone - if we are going to eventually get multiple ways to deploy OpenSDS like this, would it make sense to create repos for each. Something like opensds-salt, opensds-ansible, etc. I'd be interested to know folks thoughts on how to best structure things long term.

**Comment by xing-yang** [comment]
There is an official repo for SaltStack formulas.  Usually formulas get stored over there.  I think we can fork that repo instead of creating another repo here.

**Comment by xing-yang** [comment]
https://github.com/saltstack-formulas

**Comment by noelmcloughlin** [comment]
Thanks @leonwanghui @xing-yang @stmcginnis pls let me know how to join the community as contributor, etc.

Yes, opensds-formula can be stored in the official repo.  Does anyone know if there is official repo for ansible - I searched once but it was unclear to me.

**Comment by stmcginnis** [comment]
Oh, thanks @xing-yang. That makes sense to keep it where other salt formulas are kept. I wasn't aware of that (very limited salt experience).

I don't think there is an equivalent for ansible. At least none that I have come across so far.

**Comment by leonwanghui** [comment]
@nolemcloughlin Hi, currently there are two deployment ways: 

* [ansible](https://github.com/opensds/opensds/tree/master/contrib/ansible) script deployment for users

* [shell](https://github.com/opensds/opensds/tree/master/script/devsds) script deployment for developers

BTW, they will both be moved to standalone project after getting permitted by TSC.

**Comment by nmadhok** [comment]
Let me know when project is ready to be forked upstream to https://github.com/saltstack-formulas and I'll fork it

**Comment by xing-yang** [comment]
Thanks Nitin!

**Comment by noelmcloughlin** [comment]
Thanks, @nmadhok  Just finishing other saltstack work, then starting this.

**Comment by leonwanghui** [comment]
@noelmcloughlin @nmadhok Great, please be free to to ask if you need any help.

**Comment by leonwanghui** [comment]
Hi @noelmcloughlin @nmadhok, recently I'm working on proposing a new idea about how to simplify opensds deployment and configuration (see the [link](https://docs.google.com/presentation/d/1X-FqHhSPiu_0nV6GZqb_umlx37kpesGygMEGJRO2LvE/edit?usp=sharing)). And I think it's closely related to what you are working, so if you are interested I think we could submit a propsal that creates a new code repo to do code development onto TSC meeting. And if it gets permitted, I wish one of you could serve as PTL of this project.

Any thoughts, questions or suggestions?

**Comment by stmcginnis** [comment]
I believe saltstack-formulas is where users of Salt expect to go to be able to find formulas. I don't have much Salt experience, so correct me if I'm wrong.

If that is the case, then even though this would be OpenSDS specific, I'm not sure if being under the opensds namespace would be the best option. I suppose we could look into mirroring the same repo between the two, but I don't believe there would be an automatic way to do that.

Another option would be to just have the opensds.io website link to this from some place where potential users could discover it.

So not sure what would be best here with not really knowing how the SaltStack ecosystem works. Any recommendations @noelmcloughlin?

**Comment by xing-yang** [comment]
I just chatted with @nmadhok and he said he is interested in Leon's proposal.  Salt formulas do have an official repo, but Nitin said we can fork it to make sure it is in sync.  Leon's proposal also includes other deployment tools such as Ansible and Helm.  For Helm, there's also an official repo so we probably need to fork it as well.  We actually already talked about creating a separate repo to host all OpenSDS deployment tools and TSC has already approved that.  The only thing we have not discussed is whether to have a PTL for that, but I think we can bring it up again since it seems that there's interest from the community.  Waiting to hear back from @noelmcloughlin as well.  Thanks.

**Comment by leonwanghui** [comment]
@xing-yang IMO there is no need to fork Ansible and Helm official repo into [opensds](https://github.com/opensds) (but we can do it for communities collaboration), because we can directly download binary-built tools from them and run them without copying the source code. So (if I get it right) we could do the same thing to develop the `opensds-formulas` code in `opensds-installer` repo and install it by calling the `saltstack` tool, which is the best option for avoiding the inconsistency between opensds releases and opensds-formulas upstream. But if there are some problems to enforce it in this way, then we can consider the current option that keeps opensds source code and opensds-formulas separate.

**Comment by xing-yang** [comment]
@leonwanghui My understanding is that it's better to store salt-formulas under the official Salt repo, but I'll leave that to you, @nmadhok, and @noelmcloughlin to decide what's the best way.

**Comment by stmcginnis** [comment]
@xing-yang, I'm a bit confused by the statement "talked about creating a separate repo to host all OpenSDS deployment tools". Is there a plan to have one repo with all types of deployment tooling in it?

I would find it confusing, or at least pretty odd, to have one repo that contained ansible, helm, puppet, etc. modules, all in one place. 

In this case, I think we need to have it where saltstack users are used to going to find formulas. But the other ones I think would make more sense as separate repos for opensds-ansible, opensds-helm, opensds-pickatool.

**Comment by xing-yang** [comment]
@stmcginnis Currently we have multiple deployment tools in both Sushi and Hotpot.  Members from EUAC and TSC told us it is hard to navigate and find out which deployment tool to use.  Leon had proposed to have a common repo and move all the deployment tools in it so that user can just go to one place to install OpenSDS.  This was discussed in previous Technical Meetings and TSC meeting and everyone was onboard with that.  So this is basically to move deployment tools we already have into a common place.

I know OpenStack has different projects for different install tools, but OpenSDS is at a very early phase compared to OpenStack.  Right now OpenSDS is still a very small community so we are trying to consolidate resources and not to have too many repos and projects.

**Comment by noelmcloughlin** [comment]
Thanks for the excellent feedback, the comments are interesting.

@leonwanghui You are proposing 'SDSDS-d' ('_software defined [open] SDS deployer_")? :smiley:  Abstraction from underlying deployment technologies is important aspiration, so I support your proposal.  And @xing-yang confirms TSC agreement that the code be hosted here.

@stmcginnis, I agree ansible, puppet, helm, saltstack, etc, integrations with OpenSDS *may* live upstream.  I original propose to fork an OpenSDS formula into [official saltstack-formulas](https://github.com/saltstack-formulas) but it can be forked anywhere on github.com, [including unofficial salt-formuls repo](https://github.com/salt-formulas), if someone wishes.

My understanding therefore, is that @leonwanghui's  proposed`OpenSDS-d` (deployer) component will be part of this project, and deliver integration with ansible/salt/helm components forked into some  stable repo from a unstable/development repo, possibly a Dev branch here or upstream?

**Comment by noelmcloughlin** [comment]
[This site](https://galaxy.ansible.com/explore#/ ) appears to be an official Ansible hub for "formulas".

**Comment by leonwanghui** [comment]
@noelmcloughlin This is great, I think we can develop the `opensds-ansible` code under opensds repo, and publish the release into this Ansible Hub.

**Comment by noelmcloughlin** [comment]
I think a better name is`opensds-deployer` component/project/repo - the deployment use cases will be- install, upgrade, and uninstall, in the first iteration.  Later the Controller may require API support for other related use cases- downgrade, and backup, for example.

I think the `opensds-salt` code can be lightweight.  The following upstream building blocks could be integrated with `opensds-salt` code base, is my initial thought-

- [packages formula](https://github.com/saltstack-formulas/packages-formula) 
   This has native Linux package support, and support for newer `snap` packaging technology. Helm could be added here.
- [openssh](https://github.com/saltstack-formulas/openssh-formula)
  Keys and permitRootLogin
- [etcd formula](https://github.com/saltstack-formulas/etcd-formula)
  Distributed keystore
- [ceph formula](https://github.com/saltstack-formulas/ceph-formula)
   Software defined storage dependency
- [docker formula](https://github.com/saltstack-formulas/docker-formula)
   Depoy containers / compose

I'm am rewriting the `etcd-formula` at the moment and will raise a PR with integration with Linux, MacOS, and Windows.  @nmadhok you are more experienced with Saltstack - what are your thoughts?

thanks.

**Comment by leonwanghui** [comment]
Hi @nmadhok @noelmcloughlin , just want to know how is going on about your code development of `opensds-salt` : )

**Comment by noelmcloughlin** [comment]
Last week I worked on PR for `etcd-salt`[here](https://github.com/saltstack-formulas/etcd-formula/pull/7), since openSDS needs etcd. Ceph may will need work too.   Next few weeks are very busy time for me until after April 20th. will examine ceph next.

**Comment by leonwanghui** [comment]
@noelmcloughlin @nmadhok Hi, this is just a warm remind that the [opensds-installer](https://github.com/opensds/opensds-installer) code repo has been created and `ansible` and `helm` deploy scripts have been moved into this repo. Please be free to push it if your code is ready. Thanks!

**Comment by noelmcloughlin** [comment]
The `etcd-salt` pull request was [merged](https://github.com/saltstack-formulas/etcd-formula/pull/7).   I'm going to look at `opensds-ansible` next and Ceph next.  My intention is to reuse [ceph-formula](https://github.com/saltstack-formulas/ceph-formula) but another extremely interesting option is [DeepSea](https://github.com/SUSE/DeepSea).  I need to do some further research.

**Comment by noelmcloughlin** [comment]
Hi @leonwanghui  Sorry, no further updates. do you want to close this issue until a design/Pr proposal is ready?

**Comment by leonwanghui** [comment]
@noelmcloughlin It's ok to leave it here, I'm just wondering if this feature can be finished by late June, since we would publish the Aruba release then.

**Comment by noelmcloughlin** [comment]
hi @leonwang, it cannot be planned into Aruba, but definitely the following
release.

**Comment by leonwanghui** [comment]
Cool!

**Comment by noelmcloughlin** [comment]
@nmadhok  could you please fork [DeepSea formula](https://github.com/noelmcloughlin/deepsea-formula) to saltstack-formulas community please?  This might be useful for salt-opensds installer. Thanks.

**Comment by noelmcloughlin** [comment]
Hi all,  the following is a brief progress update on prototyping opensds deployment via Salt.

**OpenSDS Cluster Installation through SaltStack progress report.**

The following prototyping has been completed on GNU Linux (Centos and Suse) cluster.  Refer to the attached logs for pseudo-design and prototyping logs.

1. Bootstrap the SDS controller (bash script)  OK
2. Review yaml models   OK
3. Deploy SDS Controller Node (bash command to deploy salt-masters)   OK
4. Deploy SDS payloads  (bash command to deploy salt-minions)   OK

The following prototypes are outstanding:

1. Configure opensds cluster variables (Ceph, Cinder, LVM).  For CEPH backend, I think DeepSea is best solution right now. I have engaged with the upstream project (issues & pull requests).  
2. How to test opensds cluster
3. How to purge and clean opensds cluster

I hope to open a pull request on opensds-installer dev branch in one-two weeks.  A demo maybe possible  in next few weeks. 

Prototyping logs: 
[opensds-salt-poc1-notes.txt](https://github.com/opensds/opensds/files/2060500/opensds-salt-poc1-notes.txt)

Thanks for your patience.
N.

**Comment by stmcginnis** [comment]
Awesome, thanks @noelmcloughlin!

**Comment by xing-yang** [comment]
Hi @noelmcloughlin, that is great progress!  Looking forward to seeing your PR.  Thanks!

**Comment by leonwanghui** [comment]
@noelmcloughlin Well done, and BTW you can just open a PR on opensds-installer master branch directly.

**Comment by noelmcloughlin** [comment]
I have an outline framework for opensds-installer/salt support  completed. [Please see this ...](https://github.com/noelmcloughlin/opensds-installer/pull/1/files)

**Comment by xing-yang** [comment]
Thanks @noelmcloughlin !  If you have tested your PR, please go ahead and submit it so we can review it.  I noticed that you referenced your own fork in the PR.  That should be changed when you submit it?

**Comment by noelmcloughlin** [comment]
PR: https://github.com/opensds/opensds-installer/pull/13   I referenced my own fork for DeepSea (aka openATTIC) because that upstream project needs some work for GNU Linux / Distro agnostic solution.

**Comment by xing-yang** [comment]
Thanks @noelmcloughlin!
@nmadho can you help review this PR? https://github.com/opensds/opensds-installer/pull/13.  Thanks!

**Comment by leonwanghui** [comment]
Would close it : )
