### ISSUE TITLE
OpenSDS SouthBound Interface Design

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#34]
From the current version of OpenSDS southbound interface, we found that mount and unmount are operations of host, and MountVolume and UnmountVolume methods should be executed by OpenSDS Hub module rather than backend drivers, thus they should be removed from the southbound interface.

So we drafted this proposal #33  #35, aiming to make it easier for vendors to use by redesigning southbound interface.

Please speak freely if you have any questions : )

**Comment by hannibalhuang** [comment]
can not be handled by drivers seems like a mis-statement, what is the actual meaning ?

**Comment by leonwanghui** [comment]
Hi @hannibalhuang , the issue has been updated, please have a look at it.

**Comment by leonwanghui** [comment]
Resolved by PR [#79](https://github.com/opensds/opensds/pull/79).
