### ISSUE TITLE
Include documentation for use with EMC VMAX and/or Unity

### ISSUE THREAD

**Issue by howels** [opensds/opensds#349]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**: No documentation explaining how to use OpenSDS with Dell EMC VMAX or Unity

**What you expected to happen**:  Simple guide added to docs section, explaining how to configure OpenSDS with VMAX or Unity for users who wish to begin using OpenSDS.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:   There is a wide user base of VMAX and Unity users who are increasingly deploying container workloads and OpenSDS is a great choice for these users. However there is currently no instructions to introduce new users and enable them to begin to use OpenSDS with VMAX or Unity arrays.

**Environment**:
- Hotpot(release/branch) version:  Current Stable
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Current stable (recent 4.x)
- Install tools: 
- Others:

**Comment by xing-yang** [comment]
@howels Thank you for your interest in OpenSDS!  Can you please tell us a little bit about the background of this request?  Are you a customer of VMAX/Unity or you are working for Dell EMC?  Thanks!

**Comment by howels** [comment]
Hello, I work at DellEMC and I'm trying to use OpenSDS in place of CoprHD. I can locate hardware to test against if someone can provide instructions to help get OpenSDS running.

**Comment by xing-yang** [comment]
@howels Hi!  I worked at DellEMC before as well.  We are planning to have native drivers to support DellEMC storage in OpenSDS in the 2nd half of 2018.  If you want to start installing OpenSDS and get familiar with it, the easiest way is to test OpenSDS standalone with LVM backend:
    https://github.com/opensds/opensds/wiki/Local-Cluster-Installation-with-LVM
We also provide Ansible deployment tool to install OpenSDS:
    https://github.com/opensds/opensds/wiki/OpenSDS-Cluster-Installation-through-Ansible
Containerized deployment is also available here:
    https://github.com/opensds/opensds/wiki/How-to-Run-Containerized-OpenSDS-for-Testing-Work

If you are interested in learning more about OpenSDS, I'd happy to schedule a call with you.  Please let me know.  Thanks!

**Comment by leonwanghui** [comment]
Hi @howels , firstly sincerely thank you for focusing this project, and the answer for your quesiton is yes.

Currently we support three options to integrate opensds with Kubernetes:
* [external provisioner and flexvolume](https://github.com/opensds/nbp/wiki/OpenSDS-FlexVolume-and-Provisioner-Testing-Steps): This enables opensds work as the extenal storage drivers of kubernetes
* [csi plugin](https://github.com/opensds/opensds/wiki/OpenSDS-Integration-with-Kubernetes-CSI): OpenSDS has supported the latest v0.2.0 version of csi standard which is used in k8s v1.10
* [service catalog](https://github.com/opensds/nbp/blob/master/service-broker/INSTALL.md): This option can provide an elegant way of exposing opensds service (volume, snapshot, replication, etc) to kubernetes users

It's very welcomed if you want to try installing it now, and please be free to ask if you have any quesiton.

**Comment by howels** [comment]
Do you also supply templates to run the OpenSDS service containers within Kubernetes? I noticed the CSI support which is great but I only see Docker-Compose container templates which is ok for a demo but harder to manage in complex production environments.

**Comment by leonwanghui** [comment]
Good question! Currently I ‘m working for helm deployment (code is under charts folder) but not finished completely, now you can try deploy opensds service using helm but opensds csi plugin is not ready to deploy now, I can send you the helm install steps offline if you want to test it.

**Comment by howels** [comment]
That's ok. As my goal is to utilise a Storage Array with OpenSDS I will wait until support for VMAX and other devices starts to appear, then test everything at once.

**Comment by leonwanghui** [comment]
Sure, BTW could you join in opensds slack so that we can communicate more freely? You can find the link in README.md : )
