### ISSUE TITLE
When deleting volume in LVM environment, the snapshots remain in OpenSDS DB.

### ISSUE THREAD

**Issue by seiyatakei** [opensds/opensds#356]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:  
In lvm environment, it is possible to delete volume in case of the snapshot is existing. When a volume is deleted, the snapshots are also deleted. But the snapshots exist in OpenSDS DB.   
Because cinder and ceph prevent to delete volume if the snapshot is exists, this issue only happens in lvm.  

**What you expected to happen**:  
OpenSDS prevents to delete volume if the snapshots exist.  

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a volume in lvm storage pool. (osdsctl volume create)  
2. Create a snapshot of the volume. (osdsctl volume snapshot create)  
3. Delete the volume. (osdsctl volume delete)  

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @seiyatakei , this is a fatal bug for managing volume resource and thank you for finding it out. For your proposed goal, I think there are two options for solving this problem:
* Modify the force delete operation in lvm driver by removing the `-f` tag when calling the `lvremove` command
* Add the operation of checking existing resource related to volume in `dock` package, and return error if any related snapshot resource created when deleting a volume

I guess you have tested it, so could you submit a patch if you have solved it? Thanks!

**Comment by leonwanghui** [comment]
Thank you @seiyatakei  for great contribution, I will close this issue since it has been fixed.

**Comment by leonwanghui** [comment]
This issue is reopened for having not been solved by removing -f option, because it would cause some error when deleting logic volume. And this issue currently is being fixed by #362

**Comment by leonwanghui** [comment]
Fixed by #362
