### ISSUE TITLE
Installation of OpenSDS through docker-compose hangs

### ISSUE THREAD

**Issue by wjeiv** [opensds/opensds#399]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I was following steps in the opensds installation guide for using docker-compose to install.
It seems to work but keeps timing out.  Not sure if it really did start up and the docker-compose just didn't finish, or if it's really trying to wait for something that isn't happening.  Let me know if there's something else I can provide to give more detail.  Thanks.

sudo docker-compose up
bill_osdsdb_1 is up-to-date
bill_osdslet_1 is up-to-date
bill_osdsdock_1 is up-to-date
Attaching to bill_osdsdb_1, bill_osdslet_1, bill_osdsdock_1
osdsdb_1    | 2018-05-22 19:16:00.598449 I | etcdmain: etcd Version: 3.3.5
osdsdb_1    | 2018-05-22 19:16:00.601260 I | etcdmain: Git SHA: 70c872620
osdsdb_1    | 2018-05-22 19:16:00.601263 I | etcdmain: Go Version: go1.9.6
osdslet_1   | I0522 19:16:00.831572       1 auth.go:49] noauth
osdslet_1   | I0522 19:16:00.831655       1 auth.go:58] &{}
osdslet_1   | 2018/05/22 19:16:00.834 [I] http server Running on http://0.0.0.0:50040
osdsdb_1    | 2018-05-22 19:16:00.601264 I | etcdmain: Go OS/Arch: linux/amd64
osdsdb_1    | 2018-05-22 19:16:00.601267 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
osdsdb_1    | 2018-05-22 19:16:00.601273 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
osdsdb_1    | 2018-05-22 19:16:00.603388 I | embed: listening for peers on http://localhost:2380
osdsdock_1  | I0522 12:16:00.925956       7 server.go:81] Dock server initialized! Start listening on port:[::]:50050
osdsdock_1  | I0522 12:16:00.929136       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:16:00.929197       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.603416 I | embed: listening for client requests on localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605182 I | etcdserver: name = default
osdsdb_1    | 2018-05-22 19:16:00.605191 I | etcdserver: data dir = default.etcd
osdsdb_1    | 2018-05-22 19:16:00.605194 I | etcdserver: member dir = default.etcd/member
osdsdb_1    | 2018-05-22 19:16:00.605196 I | etcdserver: heartbeat = 100ms
osdsdb_1    | 2018-05-22 19:16:00.605198 I | etcdserver: election = 1000ms
osdsdb_1    | 2018-05-22 19:16:00.605200 I | etcdserver: snapshot count = 100000
osdsdock_1  | I0522 12:17:00.935296       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:17:00.935500       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:18:00.939719       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:18:00.939811       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:19:00.947580       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.605205 I | etcdserver: advertise client URLs = http://localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605207 I | etcdserver: initial advertise peer URLs = http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.605211 I | etcdserver: initial cluster = default=http://localhost:2380
osdsdock_1  | I0522 12:19:00.947895       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:20:00.957388       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:20:00.957818       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.608813 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.608830 I | raft: 8e9e05c52164694d became follower at term 0
osdsdb_1    | 2018-05-22 19:16:00.608836 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
osdsdock_1  | I0522 12:21:00.979851       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:21:00.979946       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:22:00.981566       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.608838 I | raft: 8e9e05c52164694d became follower at term 1
osdsdb_1    | 2018-05-22 19:16:00.612974 W | auth: simple token is not cryptographically signed
osdsdb_1    | 2018-05-22 19:16:00.613485 I | etcdserver: starting server... [version: 3.3.5, cluster version: to_be_decided]
osdsdock_1  | I0522 12:22:00.981645       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:23:00.983995       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:23:00.984080       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:24:00.986451       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.616458 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
osdsdb_1    | 2018-05-22 19:16:00.618103 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.809034 I | raft: 8e9e05c52164694d is starting a new election at term 1
osdsdock_1  | I0522 12:24:00.986473       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:25:00.989864       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:25:00.990066       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:26:00.993738       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.809117 I | raft: 8e9e05c52164694d became candidate at term 2
osdsdb_1    | 2018-05-22 19:16:00.809144 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
osdsdb_1    | 2018-05-22 19:16:00.809167 I | raft: 8e9e05c52164694d became leader at term 2
osdsdock_1  | I0522 12:26:00.993867       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:27:00.997656       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:27:00.997714       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:28:01.000436       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.809183 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
osdsdb_1    | 2018-05-22 19:16:00.809499 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.809585 I | etcdserver: setting up the initial cluster version to 3.3
osdsdb_1    | 2018-05-22 19:16:00.809758 I | embed: ready to serve client requests
osdsdb_1    | 2018-05-22 19:16:00.811977 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
osdsdb_1    | 2018-05-22 19:16:00.813688 N | etcdserver/membership: set the initial cluster version to 3.3
osdsdock_1  | I0522 12:28:01.000520       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:29:01.005855       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:29:01.009141       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:30:01.064180       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.813781 I | etcdserver/api: enabled capabilities for version 3.3
osdsdock_1  | I0522 12:30:01.064266       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:31:01.067030       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:31:01.067057       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:32:01.070350       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:32:01.070456       7 discovery.go:152] Backend default discovered pool sample-pool-02
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@ubuntu:~# COMPOSE_HTTP_TIMEOUT=300
root@ubuntu:~# sudo docker-compose up
bill_osdsdb_1 is up-to-date
bill_osdslet_1 is up-to-date
bill_osdsdock_1 is up-to-date
Attaching to bill_osdsdb_1, bill_osdslet_1, bill_osdsdock_1
osdsdb_1    | 2018-05-22 19:16:00.598449 I | etcdmain: etcd Version: 3.3.5
osdsdb_1    | 2018-05-22 19:16:00.601260 I | etcdmain: Git SHA: 70c872620
osdsdb_1    | 2018-05-22 19:16:00.601263 I | etcdmain: Go Version: go1.9.6
osdsdb_1    | 2018-05-22 19:16:00.601264 I | etcdmain: Go OS/Arch: linux/amd64
osdsdb_1    | 2018-05-22 19:16:00.601267 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
osdsdb_1    | 2018-05-22 19:16:00.601273 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
osdslet_1   | I0522 19:16:00.831572       1 auth.go:49] noauth
osdslet_1   | I0522 19:16:00.831655       1 auth.go:58] &{}
osdslet_1   | 2018/05/22 19:16:00.834 [I] http server Running on http://0.0.0.0:50040
osdsdb_1    | 2018-05-22 19:16:00.603388 I | embed: listening for peers on http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.603416 I | embed: listening for client requests on localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605182 I | etcdserver: name = default
osdsdb_1    | 2018-05-22 19:16:00.605191 I | etcdserver: data dir = default.etcd
osdsdb_1    | 2018-05-22 19:16:00.605194 I | etcdserver: member dir = default.etcd/member
osdsdb_1    | 2018-05-22 19:16:00.605196 I | etcdserver: heartbeat = 100ms
osdsdb_1    | 2018-05-22 19:16:00.605198 I | etcdserver: election = 1000ms
osdsdb_1    | 2018-05-22 19:16:00.605200 I | etcdserver: snapshot count = 100000
osdsdb_1    | 2018-05-22 19:16:00.605205 I | etcdserver: advertise client URLs = http://localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605207 I | etcdserver: initial advertise peer URLs = http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.605211 I | etcdserver: initial cluster = default=http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.608813 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
osdsdock_1  | I0522 12:16:00.925956       7 server.go:81] Dock server initialized! Start listening on port:[::]:50050
osdsdock_1  | I0522 12:16:00.929136       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:16:00.929197       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:17:00.935296       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:17:00.935500       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:18:00.939719       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:18:00.939811       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.608830 I | raft: 8e9e05c52164694d became follower at term 0
osdsdb_1    | 2018-05-22 19:16:00.608836 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
osdsdb_1    | 2018-05-22 19:16:00.608838 I | raft: 8e9e05c52164694d became follower at term 1
osdsdb_1    | 2018-05-22 19:16:00.612974 W | auth: simple token is not cryptographically signed
osdsdb_1    | 2018-05-22 19:16:00.613485 I | etcdserver: starting server... [version: 3.3.5, cluster version: to_be_decided]
osdsdb_1    | 2018-05-22 19:16:00.616458 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
osdsdb_1    | 2018-05-22 19:16:00.618103 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
osdsdock_1  | I0522 12:19:00.947580       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:19:00.947895       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:20:00.957388       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:20:00.957818       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.809034 I | raft: 8e9e05c52164694d is starting a new election at term 1
osdsdb_1    | 2018-05-22 19:16:00.809117 I | raft: 8e9e05c52164694d became candidate at term 2
osdsdb_1    | 2018-05-22 19:16:00.809144 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
osdsdock_1  | I0522 12:21:00.979851       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:21:00.979946       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.809167 I | raft: 8e9e05c52164694d became leader at term 2
osdsdb_1    | 2018-05-22 19:16:00.809183 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
osdsdb_1    | 2018-05-22 19:16:00.809499 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
osdsdock_1  | I0522 12:22:00.981566       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:22:00.981645       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:23:00.983995       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.809585 I | etcdserver: setting up the initial cluster version to 3.3
osdsdb_1    | 2018-05-22 19:16:00.809758 I | embed: ready to serve client requests
osdsdb_1    | 2018-05-22 19:16:00.811977 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
osdsdock_1  | I0522 12:23:00.984080       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:24:00.986451       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:24:00.986473       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.813688 N | etcdserver/membership: set the initial cluster version to 3.3
osdsdb_1    | 2018-05-22 19:16:00.813781 I | etcdserver/api: enabled capabilities for version 3.3
osdsdock_1  | I0522 12:25:00.989864       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:25:00.990066       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:26:00.993738       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:26:00.993867       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:27:00.997656       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:27:00.997714       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:28:01.000436       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:28:01.000520       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:29:01.005855       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:29:01.009141       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:30:01.064180       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:30:01.064266       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:31:01.067030       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:31:01.067057       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:32:01.070350       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:32:01.070456       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:33:01.077091       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:33:01.083595       7 discovery.go:152] Backend default discovered pool sample-pool-02
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@ubuntu:~# sudo COMPOSE_HTTP_TIMEOUT=300 docker-compose up
bill_osdsdb_1 is up-to-date
bill_osdsdock_1 is up-to-date
bill_osdslet_1 is up-to-date
Attaching to bill_osdsdb_1, bill_osdsdock_1, bill_osdslet_1
osdsdb_1    | 2018-05-22 19:16:00.598449 I | etcdmain: etcd Version: 3.3.5
osdsdb_1    | 2018-05-22 19:16:00.601260 I | etcdmain: Git SHA: 70c872620
osdsdb_1    | 2018-05-22 19:16:00.601263 I | etcdmain: Go Version: go1.9.6
osdsdb_1    | 2018-05-22 19:16:00.601264 I | etcdmain: Go OS/Arch: linux/amd64
osdsdock_1  | I0522 12:16:00.925956       7 server.go:81] Dock server initialized! Start listening on port:[::]:50050
osdsdock_1  | I0522 12:16:00.929136       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:16:00.929197       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.601267 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
osdsdb_1    | 2018-05-22 19:16:00.601273 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
osdsdb_1    | 2018-05-22 19:16:00.603388 I | embed: listening for peers on http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.603416 I | embed: listening for client requests on localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605182 I | etcdserver: name = default
osdsdb_1    | 2018-05-22 19:16:00.605191 I | etcdserver: data dir = default.etcd
osdsdb_1    | 2018-05-22 19:16:00.605194 I | etcdserver: member dir = default.etcd/member
osdsdb_1    | 2018-05-22 19:16:00.605196 I | etcdserver: heartbeat = 100ms
osdsdock_1  | I0522 12:17:00.935296       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:17:00.935500       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:18:00.939719       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:18:00.939811       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:19:00.947580       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.605198 I | etcdserver: election = 1000ms
osdsdb_1    | 2018-05-22 19:16:00.605200 I | etcdserver: snapshot count = 100000
osdsdb_1    | 2018-05-22 19:16:00.605205 I | etcdserver: advertise client URLs = http://localhost:2379
osdsdb_1    | 2018-05-22 19:16:00.605207 I | etcdserver: initial advertise peer URLs = http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.605211 I | etcdserver: initial cluster = default=http://localhost:2380
osdsdb_1    | 2018-05-22 19:16:00.608813 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.608830 I | raft: 8e9e05c52164694d became follower at term 0
osdsdb_1    | 2018-05-22 19:16:00.608836 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
osdsdb_1    | 2018-05-22 19:16:00.608838 I | raft: 8e9e05c52164694d became follower at term 1
osdsdb_1    | 2018-05-22 19:16:00.612974 W | auth: simple token is not cryptographically signed
osdslet_1   | I0522 19:16:00.831572       1 auth.go:49] noauth
osdslet_1   | I0522 19:16:00.831655       1 auth.go:58] &{}
osdslet_1   | 2018/05/22 19:16:00.834 [I] http server Running on http://0.0.0.0:50040
osdsdock_1  | I0522 12:19:00.947895       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:20:00.957388       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:20:00.957818       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:21:00.979851       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:21:00.979946       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:22:00.981566       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.613485 I | etcdserver: starting server... [version: 3.3.5, cluster version: to_be_decided]
osdsdb_1    | 2018-05-22 19:16:00.616458 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
osdsdb_1    | 2018-05-22 19:16:00.618103 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.809034 I | raft: 8e9e05c52164694d is starting a new election at term 1
osdsdb_1    | 2018-05-22 19:16:00.809117 I | raft: 8e9e05c52164694d became candidate at term 2
osdsdock_1  | I0522 12:22:00.981645       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:23:00.983995       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:23:00.984080       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:24:00.986451       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:24:00.986473       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdb_1    | 2018-05-22 19:16:00.809144 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
osdsdb_1    | 2018-05-22 19:16:00.809167 I | raft: 8e9e05c52164694d became leader at term 2
osdsdb_1    | 2018-05-22 19:16:00.809183 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
osdsdb_1    | 2018-05-22 19:16:00.809499 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
osdsdb_1    | 2018-05-22 19:16:00.809585 I | etcdserver: setting up the initial cluster version to 3.3
osdsdock_1  | I0522 12:25:00.989864       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:25:00.990066       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:26:00.993738       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:26:00.993867       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:27:00.997656       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdb_1    | 2018-05-22 19:16:00.809758 I | embed: ready to serve client requests
osdsdb_1    | 2018-05-22 19:16:00.811977 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
osdsdb_1    | 2018-05-22 19:16:00.813688 N | etcdserver/membership: set the initial cluster version to 3.3
osdsdb_1    | 2018-05-22 19:16:00.813781 I | etcdserver/api: enabled capabilities for version 3.3
osdsdock_1  | I0522 12:27:00.997714       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:28:01.000436       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:28:01.000520       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:29:01.005855       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:29:01.009141       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:30:01.064180       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:30:01.064266       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:31:01.067030       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:31:01.067057       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:32:01.070350       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:32:01.070456       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:33:01.077091       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:33:01.083595       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:34:01.114775       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:34:01.114958       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:35:01.117435       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:35:01.117502       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:36:01.120567       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:36:01.120702       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:37:01.125978       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:37:01.126012       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:38:01.128279       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:38:01.128300       7 discovery.go:152] Backend default discovered pool sample-pool-02
osdsdock_1  | I0522 12:39:01.130688       7 discovery.go:152] Backend default discovered pool sample-pool-01
osdsdock_1  | I0522 12:39:01.130711       7 discovery.go:152] Backend default discovered pool sample-pool-02
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 300).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Ubuntu 16.04

**Comment by leonwanghui** [comment]
Hi @wjeiv , can you also update the status of this issue? Thanks!

**Comment by leonwanghui** [comment]
Hi @wjeiv , I'll just close this issue for now, please be free to reopen it if you still have any question : )
