### ISSUE TITLE
Add Object-Relational Mapping (ORM) supports for database.

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#40]
**Is this a BUG REPORT or FEATURE REQUEST?**:

feature
enhancement

**What happened**:

The opensds controller only supports mysql database.

**What you expected to happen**:

I expect to support multiple database such as mysql, sqlite, postgresql etc, via adding ORM library.

**Anything else we need to know?**:

There are some libraries that implement ORM or datamapping techniques:
- [gorm](https://github.com/jinzhu/gorm) 
- [beego orm](https://github.com/astaxie/beego/tree/master/orm)

**Comment by leonwanghui** [comment]
Hi erik, I am a little confused about the motivation, can you give some detailed information or some use cases?

**Comment by wisererik** [comment]
Hi Leon, someone may like sqlite rather than mysql, so it's beter to support a variety of databases through the ORM.

**Comment by leonwanghui** [comment]
I think that's a good idea, so can you draft a PR that describes what's your plan to design ORM driver in the way like [this](https://github.com/opensds/opensds/pull/30)?

**Comment by leonwanghui** [comment]
@wisererik Hi, I noticed that this patch has been updated for a long time, can you close this issue temporarily or move it to next release?

**Comment by wisererik** [comment]
@leonwanghui thanks, I close it temporarily and will re-come up this issue in next release.
