### ISSUE TITLE
DRBD: Export of underlying backing devices

### ISSUE THREAD

**Issue by xing-yang** [opensds/opensds#426]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Currently, OpenSDS exports created devices for access. For example the
DRBD backing devices (LVM volumes) are iSCSI exported. Accessing the
underlying backing devices directly breaks DRBD. This would also
apply to every layered block devices in Linux (e.g., accessing the
underlying devices of a DM-crypt device also breaks the encryption
device; or you also do not access the underlying devices of a software
RAID. That is simply how the Linux block layer works). OpenSDS is
currently not able to handle how Linux works, namely layered block
devices. IMO, this design issue will need to be solved anyways,
otherwise layering of Linux block devices will not be possible.
Hopefully fixing the OpenSDS design then fixes this problem for DRBD.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is from https://github.com/opensds/opensds/pull/425.

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

We can create a mapping between the exported device path and DRBD device path and inform users to use the DRBD device path only.

**Comment by leonwanghui** [comment]
Hi @xxwjj , can you take a look at this issue?

**Comment by leonwanghui** [comment]
Has this issue been solved?

**Comment by leonwanghui** [comment]
Hi @xing-yang , do you know if this issue is resolved? Thanks!

**Comment by xing-yang** [comment]
No.  This is still outstanding.  Shufang and/or Jiajun are working on the design to fix this.

**Comment by xing-yang** [comment]
We have done investigation on this issue.  We don't believe this will cause data corruption.

We have two storage backends on the test setup, Huawei's Dorado storage array and LVM.  Dorado is used for the primary node, and LVM is used for the secondary node.

The primary volume created by Dorado is exposed as a block device /dev/sdb on the primary node.  /dev/drbd1 is the DRBD device path.

The secondary volume created by LVM is exposed as a block device /dev/sdb on the secondary node.  /dev/drbd1 is the DRBD device path.

User can only use /dev/drbd1 to mount a file system.  If we try to use /dev/sdb directly, we will get a device in-use error.  So this will prevent data corruption to happen as user is only allowed to use /dev/drbd1 directly.

We do need to document this behavior because user may try to use /dev/sdb directly and encounter the error.  For a remote storage array, there is no lvPath such as /dev/opensds-volumes-default/volume-xxxxxxxx in LVM, so it has to be attached to a node as a block device (i.e., /dev/sdb)  for that node to recognize it.
