### ISSUE TITLE
Admin should be able to see all volumes in Dashboard

### ISSUE THREAD

**Issue by xing-yang** [opensds/opensds#459]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
Deployed using opensds-installer ansible with CSI and LVM backend. Created a volume by "kubectl create -f nginx.yml". Volume will be shown by "osdsctl volume list", but it is not shown in Volumes when logging in as Admin in Dashboard.

**What you expected to happen**:
It should show up in Volumes when logging in as Admin in Dashboard.  Also other volumes by tenants should be displayed as well.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
@jimccfun

**Comment by leonwanghui** [comment]
resolved by [https://github.com/opensds/opensds/pull/462](https://github.com/opensds/opensds/pull/462)
