### ISSUE TITLE
Security vulnerabilities in dependencies in dashboard/package-lock.json

### ISSUE THREAD

**Issue by xing-yang** [opensds/opensds#494]
When going to opensds/opensds repo, there is a big warning shown here:

We found potential security vulnerabilities in your dependencies.
Some of the dependencies defined in dashboard/package-lock.json have known security vulnerabilities and should be updated.

We should fix this problem.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rayco-zhan** [comment]
This warning means that versions are relatively low of two modules in angular's node-modules.
1.  these components are dependent on the Dashboard development environment and have no impact on the compiled running environment.
2.  There are many dependencies between components, of which two upgrades may lead to other problems.
Therefore, I recommend maintaining the status quo and updating all Angular's node-modules in the next version.

**Comment by xing-yang** [comment]
I think we should keep this open so we don't forget to address it later.

**Comment by leonwanghui** [comment]
Close it since the dashboard part has been moved as a separate project.
