### ISSUE TITLE
confirmation email rejected

### ISSUE THREAD

**Issue by jiaohaolin** [opensds/opensds#500]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
BUG 

**What happened**:
Sorry to bother everyone in this way. I am an employee of China Mobile. I just want to join OpenSDS and figure out what it is,what it is doing for? I try to join in the maillist ,but it seems broken down, the  comfirmation email can not be send to my mailbox. It  say '550 2eeb5b4bfd4364a-b2846 Mail rejected',‘https://lists.opensds.io/account?page=bounces’
 My email is jiaohaolin@cmos.chinamobile.com

**Aother question**:
How to join the opensds.slack.com ? I'm not in you mail address list ,so it seems I can not join the communication group. What should I do ,or what should my company  do ?

**Comment by xing-yang** [comment]
Hi @jiaohaolin Welcome!  I'll send you an invite to slack.  I got notification that you have joined the mailing list.  I'll double check.

**Comment by xing-yang** [comment]
I have just sent you an invite to join slack and also confirmed your membership in the opensds-tech-discuss mailing list.  Let me know if you need anything else.

**Comment by jiaohaolin** [comment]
@xing-yang  Thanks

**Comment by leonwanghui** [comment]
So I'll consider this issue as resolved, thanks @jiaohaolin !
