### ISSUE TITLE
TestVolumeAction in contrib/cindercompatibleapi/api/volume_test.go should modify sleep call

### ISSUE THREAD

**Issue by stmcginnis** [opensds/opensds#504]
/kind bug

When running tests, the cindercompatibleapi/api tests take over 10 seconds to complete.
This appears to be because of a sleep call in TestVolumeAction that should be modified
when running unit tests to not wait. Unit test runs should not take long to complete and this
adds a long unnecessary delay.

This is in the current master and development branch hotpot code.

**Comment by leonwanghui** [comment]
Hi @BaiHuoYu , can you take a look at this issue?
