### ISSUE TITLE
Enhance dist make target for build packaging

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#505]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
For #503 , it's a good feature for building the project, but I found some issues to fix:

* `make dist` command requires `zip` and `tree` packages which is not installed in ubuntu by default
* When I performed `make clean`, the `dist` folder wasn't removed, but it should be ok
* From my perspective, `make dist` command will generate a folder called `opensds-hotpot-6172ba01-linux-amd64`, but I‘m not sure how `opensds-installer` project can detect the random number here

**What you expected to happen**:
Just my thoughts

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stmcginnis** [comment]
1. Do we have somewhere that we document which system packages need to be installed? I suppose we could add something like bindep (https://docs.openstack.org/infra/bindep/). There are a lot more than just zip and tree needed.

2. Correct. I didn't want a make clean to delete and dist output since that might still be needed and would not interfere with running make again.

3. The hash is used in the output name for local development builds. This will be used similar to `VERSION=v0.3.0 make dist` to generate an official release build.

**Comment by leonwanghui** [comment]
Hi @stmcginnis , here are some answers for your questions:

1. We don't have a unified document for demonstrating what packages should be prepared for the installation, instead we insert the installation commands of some required packages in the scripts. So I think we should enhance this area.
2. You are right, it has no impact so just keep it in this way.
3. I think we should update the command to `VERSION=v0.3.0 make dist` in opensds-installer project, what do you think?

**Comment by stmcginnis** [comment]
1. We can add a bindep format file, even if we don't actually plan to use bindep. It's at least a mostly human readable file that would give an indication of what needs to be done to get things set up. I also kind of like the idea of an ansible task that can be used to get the environment set up.

3. Actually, I don't think the installer should be calling that at all. It should use the latest released version of the projects by default. Maybe an option to have a development build installed if explicitly requested, but it really shouldn't be pulling whatever happens to be out there at the time.

**Comment by leonwanghui** [comment]
Yes, I can't agree more that the installer should enable installation from release by default, but it seems that we haven't tested that feature.
