### ISSUE TITLE
The opensds project has no roadmap and api  panorama.

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#51]
**Is this a BUG REPORT or FEATURE REQUEST?**:

help wanted

**What happened**:

Currently, the opensds project has no roadmap and api  panorama.

**What you expected to happen**:

I expect to discuss and draw up the roadmap and api panorama of the opensds project together.

**Anything else we need to know?**:

Plz refer to previous discussion on [opensds-dev](https://groups.google.com/forum/?hl=en#!topic/opensds-dev/tIObVvntSvQ)

**Comment by leonwanghui** [comment]
@wisererik Good suggestion!
I have added this issue to the open discussion part of our next meeting (refer to [here](https://docs.google.com/document/d/1OKDp7iDw_l_5kGyniqTKtrwRFAZMvItGghsxfrCqr5c/edit#)).
Hope we will have a good discussion on the meeting : )

**Comment by wisererik** [comment]
See details of the opensds controller project roadmap on [opensds wiki](https://github.com/opensds/opensds/wiki/OpenSDS-Controller-Project-Roadmap).

**Comment by leonwanghui** [comment]
Looks like this issue has been solved, so it will be closed.
