### ISSUE TITLE
The health check and status of dock

### ISSUE THREAD

**Issue by imquanquan** [opensds/opensds#517]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I deployed three dock nodes in a ceph cluster：
```
root@sds-con:/opt# osdsctl dock list
+--------------------------------------+--------------+--------------------------------+-------------------+------------+
| Id                                   | Name         | Description                    | Endpoint          | DriverName |
+--------------------------------------+--------------+--------------------------------+-------------------+------------+
| 4c4387a7-a381-5402-ae30-ff23364a812f | ceph backend | This is a ceph backend service | 10.202.5.29:50050 | ceph       |
| 30e5f409-164e-58e6-8aab-148377438abd | ceph backend | This is a ceph backend service | 10.202.5.28:50050 | ceph       |
| 2de8b1e4-dd45-59be-bcc4-091c139bd77f | ceph backend | This is a ceph backend service | 10.202.5.30:50050 | ceph       |
+--------------------------------------+--------------+--------------------------------+-------------------+------------+
```

Then,I do a stability testing for my opensds cluster.First,I kill `osdsdock` daemon in two dock node.

```
killall osdsdock
```

but,`osdsdock` still running on another on dock node:

```
root@ceph-node1:~# ps -ef | grep dock
root      9757  9684  0 10:11 pts/0    00:00:48 /opt/opensds/bin/osdsdock
root     26233 26141  0 16:28 pts/8    00:00:00 grep dock
```

Secondly,I create a `pvc` on kubernetes with OpenSDS csi plugin.

pvc.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-opensdsplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-opensdsplugin
```

I received an error when pv creating:

```
+--------------------------------------+------------------------------------------+-------------+---------+------+------------------+--------+--------+-----------+
| Id                                   | Name                                     | Description | GroupId | Size | AvailabilityZone | Status | PoolId | ProfileId |
+--------------------------------------+------------------------------------------+-------------+---------+------+------------------+--------+--------+-----------+
| 438fb090-ac52-4abf-a84f-5d40dff31b39 | pvc-c5491966-9ed2-11e8-9a81-525400245213 |             |         | 1    | default          | error  |        |           |
+--------------------------------------+------------------------------------------+-------------+---------+------+------------------+--------+--------+-----------+
```

**What you expected to happen**:

I wish the controller can make a periodic health check on the dock.When dock node down,mark it to "unavailable" status.The requests to create volume can deal with "available" dock node.

**How to reproduce it (as minimally and precisely as possible)**:

disable some dock node,then create a volume.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:v0.2.0
- OS (e.g. from /etc/os-release):Debian GNU/Linux
- Kernel (e.g. `uname -a`):4.9.0-4-amd64
- Install tools:Manual binary files

**Comment by leonwanghui** [comment]
Hi @imquanquan , first of all thanks for pointing out this critical issue, I think it's related to [#235](https://github.com/opensds/opensds/issues/235). For your question mentioned, I think the key problem is that according to the capabilities reported  by dock service, the system chose the unavailable dock service exactly. One proposed solution is that we can enable `tty` feature in etcd and detect the liveness of all dock services. And it could be appreciated if you are willing to open a PR for it : )

**Comment by imquanquan** [comment]
Thanks @leonwanghui ,I'am doing some testing for OpenSDS now,and feedback problem I encountered :）
