### ISSUE TITLE
The number of “Block Storages” in “Home” tab

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:

1. There are eight Block Storages in Home tab.
![1](https://github.com/wisererik/images/blob/master/1.png)

2. But two of Block Storages are attacher dock so the number of actual Block Storages are six. Is attacher
dock included in Block Storages?
![2](https://github.com/wisererik/images/blob/master/2.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @wisererik, I'm wondering what's the status of this issue. I'll close it for now, if u think it's still a problem please open an issue at [dashboard](https://github.com/opensds/opensds-dashboard/issues) project.
