### ISSUE TITLE
priority of command line flags vs. config

### ISSUE THREAD

**Issue by pohly** [opensds/opensds#532]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I was following the https://github.com/opensds/opensds/wiki/How-to-Run-Containerized-OpenSDS-for-Testing-Work instructions when I noticed that I had to change the ports of the etcd container because my host already had another etcd instance running which used the ports.

I changed the command line parameters, but that had no effect: osdsdock continued to use the same ports. Later I found that the example config also had settings for the etcd ports. So it looks like osdsdock ignored the command line parameters in favor of the config file (haven't checked, though).

**What you expected to happen**:

Command line parameters should have higher priority than the config file.

This is common practice, for example in https://github.com/spf13/viper#why-viper

**How to reproduce it (as minimally and precisely as possible)**:

Create a config file with a `[database]` section, then try  to override those settings with `--db-endpoint`.

**Environment**:
- Hotpot(release/branch) version: "latest" container images as of 2018-10-15.

**Comment by leonwanghui** [comment]
@pohly Thanks for pulling this issue, and @xxwjj please take a look at it, thanks!

**Comment by leonwanghui** [comment]
@pohly I think this issue has been resolved by #613, please take a look, thanks!

**Comment by leonwanghui** [comment]
Will close it, plz reopen it freely
