### ISSUE TITLE
Compiling error when building osdsdock.go

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#54]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG

**What happened**:

A few minutes ago, when I  built the opensds project with LiteIDE, it reported the error and showed
`.\osdsdock.go:88: undefined: server.ListenAndServe` 
It's caused by programming errors, but there is no suitable protective measure to help check this error.

**What you expected to happen**:

I expect to increase the build mechanism in CI to prevent compilation error.

**Comment by leonwanghui** [comment]
It seems weired for me because there is no error when I build it. And from what you described, the error may means that this method ```ListenAndServe``` in server package is not defined, but I do find this method development:
```go
func ListenAndServe(srv pb.DockServer) {
	// Find whether the type of input is supported.
	switch srv.(type) {
	case *dockServer:
		ds := srv.(*dockServer)

		// Listen the dock server port.
		lis, err := net.Listen("tcp", ds.Port)
		if err != nil {
			log.Fatalf("failed to listen: %+v", err)
			return
		}

		log.Println("Dock server initialized! Start listening on port:", ds.Port)

		// Start dock server watching loop.
		ds.Server.Serve(lis)

		defer ds.Server.Stop()
	default:
		log.Fatalln("Don't support this type!")
		return
	}
}
```
So I'm curious about what is the cause of your problem, did you change some codes associated with this method?

**Comment by wisererik** [comment]
@leonwanghui I'm sorry that I did not update local repository, It's not a problem, I will close it.
