### ISSUE TITLE
csi.server.opensds go into the zombie state

### ISSUE THREAD

**Issue by imquanquan** [opensds/opensds#556]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I perform fault testing for OpenSDS with Kubernetes and Ceph.One of test cases is simulating the Ceph **slow disk** impact on OpenSDS and Kubernetes CSI when the StatefulSet start up.The test result shows that the `csi.server.opensds` process in CSI nodeplugin container  go into the zombie state.This will cause the entire Kubernetes node to be unavailable 

**What you expected to happen**:

The Pod creating failed,but doesn't influence Kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

1. First use fio to consume disk performance:

```
fio -filename=/home/ceph/var/lib/osd/ceph-1032/test -direct=1 -iodepth 32  -rw=write -ioengine=libaio -bs=4M -size=80G  -runtime=120  -name=mytest
```

2.  Create StorageClass for OpenSDS and create a StatefulSet with 10 Pods.A pod stucks in `ContainerCreating` state when it's creating：

```
fio-test-ss-5                        1/1       Running             0          11m       172.20.1.29      10.191.157.96    <none>
fio-test-ss-6                        1/1       Running             0          11m       172.20.4.29      10.191.157.99    <none>
fio-test-ss-7                        1/1       Running             0          10m       172.20.2.30      10.191.157.97    <none>
fio-test-ss-8                        0/1       ContainerCreating   0          9m        <none>           10.191.157.98    <none>
```

3. Check Ceph and OpenSDS,the volumes are created,but check the corresponding Kubernetes node and the CSI nodeplugin logs:

```
I1123 06:45:51.633227       1 logs.go:40] 2018/11/23 06:45:51 helper.go:89: Command: blkid /dev/rbd1
I1123 06:45:51.636349       1 logs.go:40] 2018/11/23 06:45:51 helper.go:250: failed to GetFSType: exit status 2
I1123 06:45:51.636370       1 logs.go:40] 2018/11/23 06:45:51 helper.go:89: Command: mkfs -t ext4 -F /dev/rbd1
I1123 06:45:51.639745       1 logs.go:40] 2018/11/23 06:45:51 helper.go:278: failed to Format: exit status
```

Because Ceph IO stuck, `/dev/rbd1` mkfs failed.And `csi.server.opensds` go into the zombie state.

I check the rbd status,the `rbd map` process die.

```
root@k8s-node2:~# ps aux| grep server
root     124127  0.0  0.0      0     0 ?        Zsl  14:06   0:00 [csi.server.open] <defunct>
```

**Environment**:
- Hotpot(release/branch) version:v0.2.0
- OS (e.g. from /etc/os-release):Debian 8
- Kernel (e.g. `uname -a`):3.16.0-6-amd64

**Comment by leonwanghui** [comment]
I will close this issue, please reopen it if there are still some problems.
