### ISSUE TITLE
oops: sensitive information in code?

### ISSUE THREAD

**Issue by bluejumper** [opensds/opensds#562]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I found something that looked sensitive, and likely private.

**What you expected to happen**:
To notify the repository maintainers.

**How to reproduce it (as minimally and precisely as possible)**:
Open the following link in your browser: https://github.com/opensds/opensds/blob/master/pkg/db/drivers/mysql/mysql.go#L32

**Anything else we need to know?**:
I'll keep an eye out :)

**Environment**:
- Hotpot(release/branch) version: ding
- OS (e.g. from /etc/os-release): dong
- Kernel (e.g. `uname -a`): diddly
- Install tools: doo
- Others: dah

**Comment by leonwanghui** [comment]
Oh even though the password is out-of-date, still thanks for your kind remind, and we will fix it ASAP : )

**Comment by xing-yang** [comment]
Thanks for reporting the bug!
Fixed it in the development branch: https://github.com/opensds/opensds/commit/90102816ecbcc8b4178d9b8b2767be25bda279fe

Will merge it to master when we cut the Bali release.

**Comment by bluejumper** [comment]
Has been maintained 👍
