### ISSUE TITLE
osdsctl issue

### ISSUE THREAD

**Issue by bfliujinlong** [opensds/opensds#571]
**Is this a BUG REPORT or FEATURE REQUEST?**:
```shell
root@SDS:~/opensds-installer/ansible# osdsctl pool list
ERROR: parse http://{172.19.40.240}:50040/v1beta/2555954dc87746fbbfe9674ba9da5769/pools?offset=0&sortKey=id&limit=50&sortDir=desc: invalid character "{" in host name
root@SDS:~/opensds-installer/ansible# 
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @bfliujinlong , it seems that there is something wrong with host_ip configuration, can you show how you configure it? Thanks!

**Comment by leonwanghui** [comment]
@bfliujinlong I'll close this issue, please be free to reopen it.
