### ISSUE TITLE
Unnessesary title on resource module in home page

### ISSUE THREAD

**Issue by xinyan-zhang** [opensds/opensds#576]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Move the mouse to the resource module in home page, it presents a title with "resource", this is not necessary.
**What you expected to happen**:
No title present when move the mouse to the resource module in home page.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuejuSDS** [comment]
@xinyan-zhang this bug has been fixed, you can colse the issue.
