### ISSUE TITLE
dashboard volume expand dont check  expand capacity

### ISSUE THREAD

**Issue by chenpengzi** [opensds/opensds#579]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
On the dashboard,When extending a volume, OpenSDS did not check the input capacity, only enter numbers, can't enter other
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuejuSDS** [comment]
@chenpengzi this bug has been fixed
