### ISSUE TITLE
Incorrect field name of volume extend

### ISSUE THREAD

**Issue by chenpengzi** [opensds/opensds#580]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
incorrect field name of volume extend, 
origin filed: VolumeVolume
new filed: Volume Name
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuejuSDS** [comment]
Hi,@chenpengzi this bug has been fixed, you can colse the issue.
