### ISSUE TITLE
cinder driver bug

### ISSUE THREAD

**Issue by xxwjj** [opensds/opensds#581]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When I access the Emc array using cinder driver, I got an error blow:
```
root@opensds:~/gopath/src/github.com/opensds/opensds# ./build/out/bin/osdsdock --logtostderr -v 8
I1228 04:40:50.985477   22037 logs.go:75] [Info] LogFlushFrequency: 5s
I1228 04:40:50.987148   22037 server.go:81] Dock server initialized! Start listening on port:124.61.32.100:50050
I1228 04:40:51.073486   22037 cinder.go:421] Starting list pools in cinder drivers.
E1228 04:40:51.158463   22037 cinder.go:433] Cannot extract storage pools:json: cannot unmarshal number 675.567 into Go struct field Capabilities.free_capacity_gb of type int64
E1228 04:40:51.158517   22037 discovery.go:139] Call driver to list pools failed:json: cannot unmarshal number 675.567 into Go struct field Capabilities.free_capacity_gb of type int64
E1228 04:40:51.158663   22037 dock.go:81] When calling capabilty report method:There is no pool can be found.
```

So I can't start osdsdock.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Already solved by #582
