### ISSUE TITLE
 Behavior of volume reduction

### ISSUE THREAD

**Issue by fideltak** [opensds/opensds#588]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
About extend volume function, When I assign new volume size lower than current size as misoperation, the volume status is changed to "extending".
And then the volume status does not goes to "available" even though getting log "controller.go:287] new size(9) <= old size(10)".
It means when do misoperation like this, I cannot operate for that volume anymore because of the status "extending".

**What you expected to happen**:
I think it should be changed "available" status after failing extend function.

**How to reproduce it (as minimally and precisely as possible)**:
osdsctl volume extend <id> <new size> [flags]

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:  
v0.4.0  
- OS (e.g. from /etc/os-release):  
Ubuntu 18.04.1 LTS  
- Kernel (e.g. `uname -a`):  
4.15.0-43-generic
- Install tools:
- Others:

**Comment by xing-yang** [comment]
@fideltak Thanks for reporting the issue!

**Comment by xing-yang** [comment]
@xxwjj Please take a look.

**Comment by xing-yang** [comment]
@wisererik Please track this.

**Comment by xxwjj** [comment]
@xing-yang I've found that bugs. The source code has implemented volume size check process in controller(scheduler) layer, however, it do not recovery the status back to 'available' status when found the size is not right, and I think this logic should put in api layer.

IMO, There are two situations that need to be differentiated for state processing.
1. Some basic paramters checking which do not take a lot of time should be done before the status change to extending status.
2. Other action which will take a lot of time need to be put in controller layer,  and when get an error we should recovery the status back to available status(It just cann't extend the size, but the volume still healthy).

**Comment by fideltak** [comment]
Thank you for quick responses!! I will check it on this week.

**Comment by fideltak** [comment]
I confirmed It's fixed.

**Comment by xing-yang** [comment]
@fideltak Thanks!

**Comment by leonwanghui** [comment]
Thanks @fideltak !!!
