### ISSUE TITLE
Full lifecycle management of the project

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#60]
## Motivation
As we know, LCM (life-cycle management) of one project SHOULD contain these stages below: design, coding, building, testing, deployment and releasing. From this point, opensds controller project is far away from being ready for producibility. Inside these stages, we still did poor work in building, testing, deployment and releasing these four stages.
### Building
As for building work, currently we use go build tool to manage the whole project. Although it works well now, but IMO there will be more problems as this project grows.
So I suggest we add more building options (make, shell scripts and so forth) for system scalability and availability.
### Testing
A productive testing framework should contain unit test, integration test and e2e test. Right now we are trying to work on unit test, but never forget those two others. Considering there are so many mature testing frameworks, it would be a good choice if we build our integration and e2e test on popular opensource project (ginkgo etc).
### Deployment
With the development of IaaS and PaaS, automatic deployment and installation become more and more important in a distributed system cluster. As a cloud-native storage system, opensds controller project MUST support (at least one of) automatic deployment as shown below:
- Scripts
- Automatic tools (such as ansible)
- Containerization (docker, helm, bosh etc)
### Releasing
To be ready for productization, publishing a release is the necessary but complex work. Here are some references from some other popular projects ([service catalog](https://github.com/kubernetes-incubator/service-catalog/wiki/All-About-Releases), [osba](https://github.com/openservicebrokerapi/servicebroker/projects/1)) for better understanding.

Lastly, please notice that it is just some initial thoughts from my side about what a formal project should be, so more suggestions or comments are welcomed.

**Comment by leonwanghui** [comment]
Good news for this issue is that we have finished the initial development of first three parts. But I suggest we should speed it up since there is not time left.

**Comment by leonwanghui** [comment]
Here I'm execited to tell you we almost finish the famework of full project! Thanks everyone for contributing in and supporting this project!

**Comment by stevenphtan** [comment]
good job!
