### ISSUE TITLE
Encryption and decryption supports for hotpot.

### ISSUE THREAD

**Issue by lasshpanzer** [opensds/opensds#603]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Currently hotpot lacks encryption and decryption.

**What you expected to happen**:
The design ideas are as follows:
1.Add the following contents to the opensds.conf. This can be used to select the encryption and decryption kit. Currently only supports the aes encryption tool that has been implemented. Users can also implement it themselves.
```
# Encryption and decryption tool. Default value is aes.
password_decrypt_tool = aes
```
2.Provide two encryption and decryption tools. One is used for shell script calls to encrypt the password automatically, the other which does not echo the password is used for user to encrypt password that will be add to the configuration file.

3.All the passwords in the configuration files must be encrypted by encryption tool by default, otherwise the service will not start normally.

**Anything else we need to know?**:
Design proposal needs to be discussed as soon as possible.

**Environment**:
- Hotpot(release/branch) version: latest version

**Comment by leonwanghui** [comment]
Resolved bu #602
