### ISSUE TITLE
osdsdock bug parsing vgs size due to locale-dependent number format

### ISSUE THREAD

**Issue by acorbellini** [opensds/opensds#608]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
VGS formats numbers depending on current locale. Causing osdsdock to incorrectly parse the free and total size of the volumes. E.g. in spanish locale VGS returns 24,00 while in US locale it returns 24.00
**What you expected to happen**:
I expected `osdsctl pool list` to show the correct size of the backend
**How to reproduce it (as minimally and precisely as possible)**:
Follow the installation steps in the "OpenSDS Local Cluster with Multi tenants Installation" and set the locale in spanish (in my environment, ubuntu selects it as default!).

**Anything else we need to know?**:
The parsing of the volume size should be locale independent. If I change the locale to en_US, everything is fine. Thanks for the awesome work you do!
**Environment**:
- Hotpot(release/branch) version: Bali
- OS (e.g. from /etc/os-release): Ubuntu 16.04 with spanish locale (detected by default in the setup)
- Kernel (e.g. `uname -a`): 4.15.0-29
- Install tools: Followed the multitenant setup
- Others:

**Comment by leonwanghui** [comment]
That's really funny, @xxwjj would be assigned to check on it.

**Comment by xxwjj** [comment]
@acorbellini can you give me more detail infomation. BTW, how set the locale?

**Comment by leonwanghui** [comment]
@acorbellini Please take a look to see if #616 resolves this issue, thanks!

**Comment by leonwanghui** [comment]
I will close this issue considering it's already resolved, plz be free to reopen it if anything still goes wrong.
