### ISSUE TITLE
OpenSDS UI安装成功，但用户密码不对，登入不上去，怎么看日志

### ISSUE THREAD

**Issue by Chechengwen** [opensds/opensds#623]
OpenSDS UI dashboard is available at http://{your_host_ip}:8088

admin/opensds@123

用户密码不对，登入不上去，

 安装是以ubuntu16.4方式安装的，

跪求帮忙，我好登入系统看看。

**Comment by leonwanghui** [comment]
Hi @Chechengwen , as for your problem, could you offer more info, such as some log output or screencut?

**Comment by leonwanghui** [comment]
From the problem you mentioned, there could be several reasons. So here is some questions for debugging your problem:
* How were u install opensds, ansible or source code build?
* Can u check if all opensds deamon service running by executing `ps -ef |grep osds`?
* U can find the log in `/var/log/opensds/` folder.
* Can u try to use `osdsctl` (CLI tool) to test if it's working?

**Comment by Chechengwen** [comment]
Wang总，您好！
                OpenSDS UI dashboard is available at http://{your_host_ip}:8088

admin/opensds@123

用户密码不对，登入不上去，

 安装是以ubuntu16.4方式安装的，

跪求帮忙，我好登入系统看看。






ccwbbc@163.com
 
发件人： Leon Wang
发送时间： 2019-03-08 10:10
收件人： opensds/opensds
抄送： Chechengwen; Mention
主题： Re: [opensds/opensds] OpenSDS UI安装成功，但用户密码不对，登入不上去，怎么看日志 (#623)
Hi @Chechengwen , as for your problem, could you offer more info, such as some log output or screencut?

**Comment by leonwanghui** [comment]
Hi, I think it would be better if we talk offline, I will send u a email right now.

**Comment by leonwanghui** [comment]
你好我是opensds社区开发者王辉，我觉得我们可能在微信上聊更方便些，欢迎加入opensds社区中国开发者群，群二维码详见附件

Chechengwen <notifications@github.com>于2019年3月8日 周五10:27写道：

**Comment by Chechengwen** [comment]
wang总，您好！
               能看到有你的回复，太高兴了，
                 ps -ef |grep osds?
                和
                 /var/log/opensds/ folder.下的ERROR文件，帮忙看看有什么问题
                



ccwbbc@163.com
 
发件人： Leon Wang
发送时间： 2019-03-08 10:24
收件人： opensds/opensds
抄送： Chechengwen; Mention
主题： Re: [opensds/opensds] OpenSDS UI安装成功，但用户密码不对，登入不上去，怎么看日志 (#623)
From the problem you mentioned, there could be several reasons. So here is some questions for debugging your problem:
How were u install opensds, ansible or source code build?
Can u check if all opensds deamon service running by executing ps -ef |grep osds?
U can find the log in /var/log/opensds/ folder.
Can u try to use osdsctl (CLI tool) to test if it's working?
