### ISSUE TITLE
有没有人管了，我在中国很想把OPENSDS用起来，但ubuntun16.4的方式安装后，在页面输入admin/opensds@123登入不了，报 Internal Server Error!

### ISSUE THREAD

**Issue by Chechengwen** [opensds/opensds#624]
有没有人管了，我在中国很想把OPENSDS用起来，但ubuntun16.4的方式安装后，在页面输入admin/opensds@123登入不了，报 Internal Server Error!

**Comment by leonwanghui** [comment]
please discuss it in #623
