### ISSUE TITLE
Cannot get metadata field when volume creation

### ISSUE THREAD

**Issue by fideltak** [opensds/opensds#625]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
CreateVolumeOpts.GetMetadata() seems not able to get metadata field in JSON body when making new volume.  
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/opensds/opensds/master/openapi-spec/swagger.yaml#/Block%20volumes/post_v1beta__projectId__block_volumes
  

```
{
  "name": "nimble-test",
  "description": "this is test",
  "size": 2,
  "availabilityZone": "nimble",
  "poolId": "0a711e7a4478b46672000000000000000000000001",
  "metadata": {
    "key1": "value1",
    "key2": "value2"
  }
}
```

**What you expected to happen**:
I want to get below metadata field in my custom driver code.
```
....
  "metadata": {
    "key1": "value1",
    "key2": "value2"
  }
....
```

**How to reproduce it (as minimally and precisely as possible)**:
Use CreateVolumeOpts.GetMetadata() in github.com/opensds/opensds/pkg/dock/proto.pb.go and POST JSON included "matadata: {}".

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:  
v0.5.0
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`):
4.15.0-46-generic
- Install tools:
- Others:

**Comment by xing-yang** [comment]
@wisererik Can you take a look of this?  Thanks.

**Comment by wisererik** [comment]
@fideltak Hi fideltak, thank you for your question, I have already submit PR to solve this issue.

**Comment by leonwanghui** [comment]
Hi @fideltak , I think this bug has been fixed now, please take a test, thx!

**Comment by fideltak** [comment]
@wisererik ,@leonwanghui 
Thanks. I just checked it has fixed.
