### ISSUE TITLE
PUT operation for profiles should not allow to change​ all the properties of profile

### ISSUE THREAD

**Issue by Shruthi-MN** [opensds/opensds#633]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
PUT operation for profile allowing to change/modify all the properties of profile
PUT /v1beta/{projectId}/profiles/{profileId}
Example:
{
  "name": "string",
  "storageType": "string",
  "description": "string",
  "provisioningProperties": {
    "dataStorage": {
      "recoveryTimeObjective": 0,
      "provisioningPolicy": "string",
      "isSpaceEfficient": true
    },
    "ioConnectivity": {
      "accessProtocol": "string",
      "maxIOPS": 0,
      "maxBWS": 0
    }
  },
  "replicationProperties": {
    "dataProtection": {
      "isIsolated": true,
      "minLifetime": "string",
      "RecoveryGeographicObjective": "string",
      "RecoveryPointObjectiveTime": "string",
      "RecoveryTimeObjective": "string",
      "ReplicaType": "string"
    },
    "replicaInfos": {
      "replicaUpdateMode": "string",
      "consistencyEnalbed": true,
      "replicationPeriod": "string",
      "replcationBandwidth": 0
    }
  },
  "snapshotProperties": {
    "schedule": {
      "datetime": "2019-03-20T17:38:43.026Z",
      "occurrence": "string"
    },
    "replicaInfos": {
      "number": 0,
      "duration": 0
    },
    "topology": {
      "bucket": "string"
    }
  },
  "dataProtectionProperties": {
    "dataProtection": {
      "isIsolated": true,
      "minLifetime": "string",
      "RecoveryGeographicObjective": "string",
      "RecoveryPointObjectiveTime": "string",
      "RecoveryTimeObjective": "string",
      "ReplicaType": "string"
    },
    "consistencyEnalbed": true
  },
  "customProperties": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  }
}
**What you expected to happen**:
It should allow to change/modify only name and description, technically allowing to change all the properties will be difficult 
PUT /v1beta/{projectId}/profiles/{profileId}
{
  "name": "string",
  "description": "string"
}

**How to reproduce it (as minimally and precisely as possible)**:
Send all the properties in request body to modify the existing profile

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
That's a good question, actually currently we don't support PUT operation on profile from both `osdsctl` and UI dashboard. But we should definitely fix that.

**Comment by leonwanghui** [comment]
@wisererik Please take a look at this issue.

**Comment by skdwriting** [comment]
@Shruthi-1MN please check it again and close.

**Comment by Shruthi-1MN** [comment]
Actual code works fine, but this confusion was because of swagger file. I am modifying the swagger file in the PR https://github.com/opensds/opensds/pull/769. So you can close the issue.

**Comment by skdwriting** [comment]
@Shruthi-1MN , as discussed, i am closing. PR #769.
