### ISSUE TITLE
Cannot unmarshal metadata field in Http request body

### ISSUE THREAD

**Issue by fideltak** [opensds/opensds#642]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When I try to make a volume via OpenSDS controller API, get error response with message.  

**{"code":400,"message":"parse volume request body failed: json: cannot unmarshal bool into Go struct field VolumeSpec.metadata of type string"}**

HTTP POST request body is  
```
{
  "name": "nimble-test",
  "size": 2,
  "availabilityZone": "tak-nimble",
  "poolId": "84a0a85b-ae13-5a65-a4dc-abbf40d6cd77",
  "metadata":{
  	"online":false,
  	"limit_mbps":100
  }
}
```
I guess metadata field only accept string. The type would be not map[string]interface{} but map[string]string. So bool or int cannot be accepted. 

**What you expected to happen**:
Metadata should accept various type of data.

**How to reproduce it (as minimally and precisely as possible)**:
Put bool value into metadata field in API request body.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
v0.5.1
- OS (e.g. from /etc/os-release):
- Ubuntu 18.04.1 LTS
Kernel (e.g. uname -a):
- 4.15.0-46-generic
- Install tools:
Others:

**Comment by xxwjj** [comment]
@fideltak thanks for your questions, I will fix it as soon as possible.BTW, metadata is not recommended to be use by  user, it only supposed to be used by driver store some extra data.

**Comment by fideltak** [comment]
@xxwjj Thank you for your advice. I try to send storage vendor specific options which not defined in CreateVolumeOpts by using Metadata field via API....  
Any easy way other than metadata?

**Comment by xing-yang** [comment]
@fideltak Is it possible to define these in the profile so create volume will have access to it?

**Comment by fideltak** [comment]
@xing-yang I tried to create custom profile to send vendor specific values by using customProperties like adding below values into my custom profile.
```
        "customProperties": {
            "nimble": {
                "online": "yes"
            }
        }
```
But I got error from osdslet when create volume with my custom profile.
```
I0405 06:43:15.243610   66110 filter.go:99] pool: default doesn't provide capability: nimble
E0405 06:43:15.244627   66110 selector.go:138] Filter supported pools failed: no available pool to meet user's requirement
```
Can I use customProperties in profile at current version?

**Comment by xing-yang** [comment]
@fideltak What is the profile name you created?  The error message suggested that the profile passed in is "default".  Can you show the whole content of your profile?

**Comment by fideltak** [comment]
@xing-yang the profile is  
```
    {
        "id": "593d4f34-9d38-47c9-90ed-7027797a61dd",
        "createdAt": "2019-04-05T14:15:41",
        "updatedAt": "",
        "name": "nimble01",
        "storageType": "hpe_nimble",
        "provisioningProperties": {
            "dataStorage": {
                "isSpaceEfficient": false
            },
            "ioConnectivity": {}
        },
        "replicationProperties": {
            "dataProtection": {
                "isIsolated": false
            },
            "replicaInfos": {}
        },
        "snapshotProperties": {
            "schedule": {},
            "retention": {},
            "topology": {}
        },
        "dataProtectionProperties": {
            "dataProtection": {
                "isIsolated": false
            }
        },
        "customProperties": {
            "nimble": {
                "online": "yes"
            }
        }
    }
```
And I used it in volume create request.  
```
{
  "name": "test-vo01",
  "size": 2,
  "availabilityZone": "tak-nimble",
  "poolId": "84a0a85b-ae13-5a65-a4dc-abbf40d6cd77",
  "profileId": "593d4f34-9d38-47c9-90ed-7027797a61dd"
}
```
after that, got msg from osdslet.  
```
I0405 14:17:04.670350   72391 controller.go:96] Controller server receive create volume request, vr =id:"a451b392-f265-46c2-9272-8e25f44a2a99" name:"test-vo01" size:2 availabilityZone:"tak-nimble" profileId:"593d4f34-9d38-47c9-90ed-7027797a61dd" poolId:"84a0a85b-ae13-5a65-a4dc-abbf40d6cd77" context:"{\"auth_token\":\"\",\"user_id\":\"\",\"tenant_id\":\"e93b4c0934da416eb9c8d120c5d04d96\",\"domain_id\":\"\",\"user_domain_id\":\"\",\"project_domain_id\":\"\",\"is_admin\":true,\"read_only\":\"\",\"show_deleted\":\"\",\"request_id\":\"\",\"resource_uuid\":\"\",\"overwrite\":\"\",\"roles\":null,\"user_name\":\"\",\"project_name\":\"\",\"domain_name\":\"\",\"user_domain_name\":\"\",\"project_domain_name\":\"\",\"is_admin_project\":false,\"service_token\":\"\",\"service_user_id\":\"\",\"service_user_name\":\"\",\"service_user_domain_id\":\"\",\"service_user_domain_name\":\"\",\"service_project_id\":\"\",\"service_project_name\":\"\",\"service_project_domain_id\":\"\",\"service_project_domain_name\":\"\",\"service_roles\":\"\",\"token\":\"\",\"uri\":\"/v1beta/e93b4c0934da416eb9c8d120c5d04d96/block/volumes\"}" 
I0405 14:17:04.673939   72391 filter.go:99] pool: opensds-volumes-default doesn't provide capability: nimble
I0405 14:17:04.674548   72391 filter.go:99] pool: default doesn't provide capability: nimble
E0405 14:17:04.674765   72391 selector.go:138] Filter supported pools failed: no available pool to meet user's requirement
```

**Comment by xing-yang** [comment]
@fideltak do you have a config yaml file for your storage?  How does that look like?

**Comment by xing-yang** [comment]
@xxwjj This might be a bug in the code.  Can you take a look?

**Comment by fideltak** [comment]
@xing-yang Do you mean the yaml in /etc/opensds/driver?
```
authOptions:
  endpoints: https://192.168.50.11:5392/v1,https://192.168.50.12:5392/v1
  username: admin
  password: *******
  insecure: true
```
opensds.conf is below for just in case...
```
[lvm]
name = lvm
description = LVM Test
driver_name = lvm
config_path = /etc/opensds/driver/lvm.yaml

[hpe_nimble]
name = hpe_nimble
description = HPE Nimble Driver
driver_name = hpe_nimble
config_path = /etc/opensds/driver/hpe_nimble.yaml

[osdsapiserver]
api_endpoint = 0.0.0.0:50040
auth_strategy = noauth
# If https is enabled, the default value of cert file
# is /opt/opensds-security/opensds/opensds-cert.pem, 
# and key file is /opt/opensds-security/opensds/opensds-key.pem
https_enabled = False
beego_https_cert_file =
beego_https_key_file =

[osdslet]
api_endpoint = 192.168.80.21:50049

[osdsdock]
api_endpoint = 192.168.80.21:50050
# Specify which backends should be enabled, sample,ceph,cinder,lvm and so on.
enabled_backends = hpe_nimble

[database]
endpoint = 192.168.80.21:62379,192.168.80.21:62380
driver = etcd
```

**Comment by xing-yang** [comment]
@fideltak Yes.  I think you need pool information in the yaml file.  It needs to match what's in the profile.  See this example here:

https://github.com/opensds/opensds/blob/master/contrib/drivers/huawei/fusionstorage/testdata/fusionstorage.yaml

Your customProperties should be under "advanced".

**Comment by xing-yang** [comment]
@fideltak We found a bug.  @xxwjj is working on a fix.  Will let you know once the fix is available.

**Comment by leonwanghui** [comment]
Hi @fideltak @xing-yang , this issue has been solved, please take a test at the latest code : )

**Comment by xing-yang** [comment]
Hi @fideltak, PR #648 fixed this issue.  Can you please give a try?  Thanks.

**Comment by fideltak** [comment]
@xxwjj @xing-yang OK, Thanks. let me check.

**Comment by xing-yang** [comment]
Hi @fideltak , have you got a chance to test this fix?  Thanks.

**Comment by fideltak** [comment]
@xing-yang , It looks fixed. thx.

**Comment by xing-yang** [comment]
That's awesome!  Thanks @fideltak!
