### ISSUE TITLE
Missing authority validation for file share and metrics API

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#701]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
For #687 #694 and #698 , some keystone policy configuration should be configured under [policy.json](https://github.com/opensds/opensds/blob/master/examples/policy.json), or else the authority validation would fail when authenticating with Keystone service.

**What you expected to happen**:
Add some policy configuration in [policy.json](https://github.com/opensds/opensds/blob/master/examples/policy.json) for file share and metrics API.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
@skdwriting @xing-yang Please take a look, thanks!

**Environment**:
- Hotpot(release/branch) version: development
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: Any (devsds, ansible)
- Others:

**Comment by leonwanghui** [comment]
Partly (metrics API) resolved by #775

**Comment by xing-yang** [comment]
Partly addressed by: https://github.com/opensds/opensds/pull/796

**Comment by skdwriting** [comment]
@Shruthi-1MN , please check and add a consolidated comment here before we close

**Comment by Shruthi-1MN** [comment]
Missing authority validation for file share APIs is done in PR #796 and for metrics API is done in  PR #775. Hence i am closing the issue.
