### ISSUE TITLE
Telemetry: GenericResponseResult is omitting value "0" in the response or urmarshell

### ISSUE THREAD

**Issue by NajmudheenCT** [opensds/opensds#706]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Yes
kind: bug

**What happened**:
I have noticed the marshalled result from msgJSON, _ := json.Marshal(resMsg) call in GenericResponseResult function omitting valur field if the value is "0" 
example : 
resMsg = {interface {} | *[]github.com/opensds/opensds/pkg/model.MetricSpec} len:2, cap:2
 0 = {github.com/opensds/opensds/pkg/model.MetricSpec} 
  InstanceID = {string} "loop0"
  InstanceName = {string} "loop0"
  Job = {string} ""
  Associator = {map[string]string} nil
  Source = {string} "Node"
  Component = {string} ""
  Name = {string} "OpensSDS_Volume_IOPS_tps"
  Unit = {string} ""
  IsAggregated = {bool} false
  MetricValues = {[]*github.com/opensds/opensds/pkg/model.Metric} len:1, cap:1
   0 = {*github.com/opensds/opensds/pkg/model.Metric | 0xc000326230} 
    Timestamp = {int64} 1556803561
    Value = {float64} 0

output 
msgJSON=
[{"instanceID":"loop0","instanceName":"loop0","source":"Node","name":"OpensSDS_Volume_IOPS_tps","metricValues":[{"timestamp":1556803561}]},
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Give GET metric API call for metric which has value 0

**Anything else we need to know?**:
NA
**Environment**:
- Hotpot(release/branch) version: capri development
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS 
- Kernel (e.g. `uname -a`):4.18.0-17-generic #18~18.04.1-Ubuntu
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @NajmudheenCT, can u pull a PR to solve it?

**Comment by hirokikmr** [comment]
Hi, @leonwanghui , @NajmudheenCT , I have similar issue in 'GET pools' REST-API response.
When "freeCapacity" is "0", "freeCapacity" is omitted in the response as follows.
Is it the same cause?

```
{
  "id": "e08835e1-edef-5f51-acf9-44126407ddf2",
  "createdAt": "2019-05-13T18:56:08",
  "updatedAt": "",
  "name": "test-pool",
  "dockId": "b0b68853-17ed-5c80-a5f1-97c967249934",
  "availabilityZone": "default",
  "totalCapacity": 365,
  "multiAttach": false,
  "storageType": "block",
  "extras": {
    "dataStorage": {
      "provisioningPolicy": "Thick",
      "isSpaceEfficient": false
    },
    "ioConnectivity": {
      "accessProtocol": "iscsi",
      "maxIOPS": 1000
    },
    "dataProtection": {
      "isIsolated": false
    },
    "advanced": {
      "diskType": "SSD",
      "throughput": 1000
    }
  },
  "replicationType": "HostBased",
  "replicationDriverName": "drbd"
}
```

**Comment by xing-yang** [comment]
Looks like a bug.  @leonwanghui PTAL.  Thanks.

**Comment by leonwanghui** [comment]
Hi, the reason why the JSON body is omit is because we defined a `omitempty` tag in each field of structure, that would let system skip marshal those fields which is empty, but if you do unmarshal you will find the field would be back with 0 value.

**Comment by leonwanghui** [comment]
Any update on this issue?

**Comment by NajmudheenCT** [comment]
I will be starting on this next week

**Comment by skdwriting** [comment]
@NajmudheenCT please check and close
