### ISSUE TITLE
Volume attach option cannot get correct specified access protocol 

### ISSUE THREAD

**Issue by fideltak** [opensds/opensds#707]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When execute volume attachment via API request like below body, `pb.CreateVolumeAttachmentOpts.GetAccessProtocol()` outputs "iscsi" even though specified "fibre_channel".
```
{
  "name": "sample-volume-attachment",
  "description": "This is a sample volume attachment for testing",
  "volumeId": "1a32ab20-7801-48a2-9298-a768a11b9b1e",
  "mountpoint": "/mnt",
  "userId": "777",
  "hostInfo": {
    "platform": "ubuntu",
    "osType": "linux",
    "ip": "172.16.2.53",
    "host": "osds02",
    "initiator": "21:00:00:e0:8b:05:05:04 "
  },
  "AccessProtocol": "fibre_channel"
}
```
However I can get AccessProtocol as "fibre_channel" in response body.
```
{
    "id": "12383020-00e3-48b8-8775-b48ebcdaada6",
    "createdAt": "2019-05-03T05:31:40",
    "updatedAt": "",
    "tenantId": "e93b4c0934da416eb9c8d120c5d04d96",
    "userId": "777",
    "volumeId": "1a32ab20-7801-48a2-9298-a768a11b9b1e",
    "mountpoint": "/mnt",
    "status": "creating",
    "metadata": {
        "Group": "grp01",
        "Iqn": "iqn.2007-11.com.nimblestorage:1a32ab20-7801-48a2-9298-a768a11b9b1e-v4831f4cd0455709c.00000031.4c648451",
        "LunId": "064831f4cd0455709c000000000000000000000031",
        "PoolId": "0a4831f4cd0455709c000000000000000000000001"
    },
    "hostInfo": {
        "platform": "ubuntu",
        "osType": "linux",
        "ip": "172.16.2.53",
        "host": "osds02",
        "initiator": "21:00:00:e0:8b:05:05:04 "
    },
    "connectionInfo": {
        "data": {
            "attachment": "attachment"
        },
        "additionalProperties": {
            "attachment": "attachment"
        }
    },
    "accessProtocol": "fibre_channel"
}
```

**What you expected to happen**:
I want to get correct AccessProtocol by using `pb.CreateVolumeAttachmentOpts.GetAccessProtocol()`.  

**How to reproduce it (as minimally and precisely as possible)**:
You may be able to see same issue when put http request like above example body.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xing-yang** [comment]
@xxwjj Please take a look.

**Comment by leonwanghui** [comment]
@fideltak You mean you can get  the right answer in the response but got the wrong access_protocol inside controller module, right?

**Comment by leonwanghui** [comment]
@fideltak Oh I guess I have found the reason, if you look at [here](https://github.com/opensds/opensds/blob/development/pkg/controller/controller.go#L324), the accessProtocol value is fetched from `StoragePoolSpec` structure, so you need to configure the `AccessProtocol` field in pool config file.

**Comment by fideltak** [comment]
@leonwanghui Thanks! I missed it...
