### ISSUE TITLE
issue with osdsctl 

### ISSUE THREAD

**Issue by daramosch** [opensds/opensds#719]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

ERROR:
<!DOCTYPE html>
<html lang="en">
        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                <title>Not Found</title>
                <style type="text/css">
                        * {
                                margin:0;
                                padding:0;
                        }

                        body {
                                background-color:#EFEFEF;
                                font: .9em "Lucida Sans Unicode", "Lucida Grande", sans-serif;
                        }

                        #wrapper{
                                width:600px;
                                margin:40px auto 0;
                                text-align:center;
                                -moz-box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                                -webkit-box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                                box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                        }

                        #wrapper h1{
                                color:#FFF;
                                text-align:center;
                                margin-bottom:20px;
                        }

                        #wrapper a{
                                display:block;
                                font-size:.9em;
                                padding-top:20px;
                                color:#FFF;
                                text-decoration:none;
                                text-align:center;
                        }

                        #container {
                                width:600px;
                                padding-bottom:15px;
                                background-color:#FFFFFF;
                        }

                        .navtop{
                                height:40px;
                                background-color:#24B2EB;
                                padding:13px;
                        }

                        .content {
                                padding:10px 10px 25px;
                                background: #FFFFFF;
                                margin:;
                                color:#333;
                        }

                        a.button{
                                color:white;
                                padding:15px 20px;
                                text-shadow:1px 1px 0 #00A5FF;
                                font-weight:bold;
                                text-align:center;
                                border:1px solid #24B2EB;
                                margin:0px 200px;
                                clear:both;
                                background-color: #24B2EB;
                                border-radius:100px;
                                -moz-border-radius:100px;
                                -webkit-border-radius:100px;
                        }

                        a.button:hover{
                                text-decoration:none;
                                background-color: #24B2EB;
                        }

                </style>
        </head>
        <body>
                <div id="wrapper">
                        <div id="container">
                                <div class="navtop">
                                        <h1>Not Found</h1>
                                </div>
                                <div id="content">
                                        <br>The page you have requested has flown the coop.<br>Perhaps you are here because:<br><br><ul><br>The page has moved<br>The page no longer exists<br>You were looking for your puppy and got lost<br>You like 404 pages</ul>
                                        <a href="/" title="Home" class="button">Go Home</a><br />

                                        <br>Powered by beego 1.11.1
                                </div>
                        </div>
                </div>
        </body>
</html>

**What you expected to happen**:
pool list output

**How to reproduce it (as minimally and precisely as possible)**:
any command using osdsctl is producing the error

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:2.4.6.0
- OS (e.g. from /etc/os-release):
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
#140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
ansible playbook
- Others:

Dashboard is not picking up my LVM BAckend either

**Comment by xing-yang** [comment]
Hi @daramosch, thanks for testing OpenSDS and opening an issue!  The bug description said Hotpot version is 2.4.6.0, but the latest release is v0.5.1:
    https://github.com/opensds/opensds/releases

I wonder where it shows 2.4.6.0?  Can you also please provide the LVM yaml file?  Thanks.

**Comment by daramosch** [comment]
Hi Xing! Thanks for the Quick Reply, Sorry I believe that is the ansible playbook version. Checked on the hotpot release and states:
###########
# RELEASE #
###########

# If user specifies intalling from release,then he can choose the specific version
hotpot_release: v0.5.1 # The version should be at least v0.2.1

Here is also my LVM YAML: 

tgtBindIp: My Server IP # change tgtBindIp to your real host ip, run 'ifconfig'                                                                              to check
tgtConfDir: /etc/tgt/conf.d
pool:
  opensds-volumes: # change pool name same to vg_name, but don't change it if yo                                                                             u choose ceph backend
    storageType: block
    availabilityZone: default
    extras:
      dataStorage:
        provisioningPolicy: Thin
        isSpaceEfficient: false
      ioConnectivity:
        accessProtocol: iscsi
        maxIOPS: 7000000
        maxBWS: 600
      advanced:
        diskType: SSD
        latency: 5ms

Now the dashboard had never picked up the LVM Backend, but the osdsctl was working fine a few days ago

**Comment by xing-yang** [comment]
I see that "tgtBindIp" is not modified.  It should be the IP address of the server where you are running the ansible script.

In the following file, change host_ip to your server ip address and re-run the ansible script.  It should set the host_ip in group_vars/lvm/lvm.yaml and group_vars/common.yml automatically for you.

https://github.com/opensds/opensds-installer/blob/master/ansible/script/global_vars.sh#L22

**Comment by daramosch** [comment]
Hi Xing, I modified the output so my IP is not visible. I did modified the entry

**Comment by xing-yang** [comment]
Did you export the opensds endpoint?  Are you using keystone?  Can you log into dashboard?
https://github.com/opensds/opensds/wiki/OpenSDS-Cluster-Installation-through-Ansible#opensds-cli

**Comment by leonwanghui** [comment]
@daramosch Here is some potential cause from my side:
* Didn't export `OPENSDS_ENDPOINT` in the right style, which should be `http://{server_ip}:50040`
* If installed from keystone (it should be by default), you need to export some keystone environment variables, but it depends on which way you specified, source code or container?

Last question is which branch of opensds-installer you are using?

**Comment by daramosch** [comment]
@xing-yang Hi! I did export the Opensds_endpoint, I am using Keystone and I am able to login to the dashboard. I did create an LVM Backend Pool using an Storage Array Volume. I am able to list the pool and volumes using osdsctl pool list and volume list commands. 

However When I access the OpenSDS Dashboard. I am not able to see any volumes.

**Comment by xing-yang** [comment]
Hi @daramosch , I assume you run osdsctl and log into dashboard both as admin?  In the dashboard, can you see the LVM pool?  Can you create a profile and try to create a volume?

**Comment by daramosch** [comment]
Hi @xing-yang , yes I am using the admin credentials and was able to create volumes and a profile from osdsctl, but i am not seeing the pool neither the volume on the dashboard. 
![Capture1](https://user-images.githubusercontent.com/33700305/57791212-8877d600-76f9-11e9-9782-86a9387f0ac4.JPG)
![Capture](https://user-images.githubusercontent.com/33700305/57791223-8dd52080-76f9-11e9-9bde-92353b4dae6e.JPG)

**Comment by xing-yang** [comment]
That is weird.  I wonder if the database is messed up due to multiple ansible installation runs.  @leonwanghui do you have any suggestions?

**Comment by daramosch** [comment]
I thought the same about the ansible installation, but this is a brand new VM I just commission and install from scratch and still the lack of visibility on the dashboard persists

**Comment by leonwanghui** [comment]
@daramosch Did you use the latest version of opensds-dashboard, could u try `docker pull opensdsio/dashboard:latest` to see if it's ood? Thanks!

**Comment by leonwanghui** [comment]
And also another suggestion is you could upgrade your installation version to v0.5.2 which is the latest version, you can achieve it by pulling the latest version of opensds-installer.

**Comment by leonwanghui** [comment]
Hi @daramosch, any update on this issue?

**Comment by leonwanghui** [comment]
Will close this issue for now, @daramosch plz be free to reopen it.
