### ISSUE TITLE
Can not set osdsdock api-endpoint using configuration file

### ISSUE THREAD

**Issue by hirokikmr** [opensds/opensds#722]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I used following configuration. (osdsdock api_endpoint is '0.0.0.0:50051')
But osdsdock used default api_endpoint configuration( '0.0.0.0:50050')
/etc/opensds/opensds.conf
```
[lvm]
name = lvm
description = LVM Test
driver_name = lvm
config_path = /etc/opensds/driver/lvm.yaml

[osdsapiserver]
api_endpoint = 0.0.0.0:50040
auth_strategy = noauth
# If https is enabled, the default value of cert file
# is /opt/opensds-security/opensds/opensds-cert.pem,
# and key file is /opt/opensds-security/opensds/opensds-key.pem
https_enabled = False
beego_https_cert_file =
beego_https_key_file =

[osdslet]
api_endpoint = 0.0.0.0:50049

[osdsdock]
api_endpoint = 0.0.0.0:50051
# Specify which backends should be enabled, sample,ceph,cinder,lvm and so on.
enabled_backends = lvm

[database]
endpoint = 0.0.0.0:62379,0.0.0.0:62380
driver = etcd
```
**What you expected to happen**:
Can set osdsdock api-endpoint using configration file

**How to reproduce it (as minimally and precisely as possible)**:
1. Change  configuration for osdsdock api-endpoint
2. Start osdsdock

**Anything else we need to know?**:
I think cause of this issue is constants are specified in the following code.
https://github.com/opensds/opensds/blob/291b4ff7f4724ea7ebb6894e56274b2a22a0e44a/cmd/osdsdock/osdsdock.go#L56

**Environment**:
- Hotpot(release/branch) version: development branch (1a13191a90cc38407e977240b2c550d23b10cf6b)
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Yes, the reason why we set it as a static IP and address is from [here](https://github.com/opensds/design-specs/blob/master/specs/capri/DNS_Resolution_Proposal_in_Hotpot.md), so I'm curious why you want to change the listen IP of osdsdock service, we are glad to set it as configurable if there are some use cases.

**Comment by hirokikmr** [comment]
@leonwanghui  Thank you for your reply.
I want to start multiple osdsdock services in one server. So I want to change the listen port of osdsdock.
I think there are some use case. For example managing multiple storage, such as lvm, and ceph, in one server or starting both attacher and provisioner osdsdock service for using the server resources effectively.

**Comment by leonwanghui** [comment]
@In your usecase, I suggest you deploy one osdsdock, but config enabled_backends with several backend types (such like `enabled_backends=lvm,ceph`).

**Comment by hirokikmr** [comment]
@leonwanghui 
Thank you for your suggestion! I was mistaken about the config enabeled_backends.

Please let me add information about another use case, it is according to the following doc(2.2.4 Configure Host-based replication).
https://github.com/opensds/opensds/blob/master/docs/readthedocs/installation/OpenSDS%20Bali%20POC%20Deployment.pdf

**Comment by leonwanghui** [comment]
@xing-yang PTAL, thanks!

**Comment by xing-yang** [comment]
Hi @hirokikmr are you referring to the following section on host-based replication config setting?  Are you not able to add an attacher dock this way?

[osdsdock]
api_endpoint = 192.168.2.2:50051 
log_file = /var/log/opensds/osdsdock.log 
bind_ip = 192.168.2.2
dock_type = attacher

**Comment by leonwanghui** [comment]
Hi @hirokikmr, any update on this issue? If not, please close it : )

**Comment by hirokikmr** [comment]
@leonwanghui @xing-yang 
I retried the configration.
When I set "dock_type" to "attacher", the api_endpoints of osdsdock is able to change. 
I'm sorry for my lack of confirmation.
Thank you for your support!
