### ISSUE TITLE
Pre-defined Profile Properties should not be required

### ISSUE THREAD

**Issue by xing-yang** [opensds/opensds#729]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Should not make profile.ProvisioningProperties required.  We can have a default for required parameters and also honor custom properties.

https://github.com/opensds/opensds/pull/725/files#diff-1d289dce075e3324bbff9b3b953639e0R63

profile.ProvisioningProperties

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
It is to check the StorageAccessCapability, if we won't follow the order then it will consider it as custom property so just to follow the order of properties specification i have added ProvisioningProperties and datastorage. Those are all not pre-defined. Admin still can add custom properties.

**Comment by skdwriting** [comment]
@PravinRanjan10 / @Shruthi-1MN can you please check and close this issue?

**Comment by Shruthi-1MN** [comment]
@xing-yang , I have added the changes in the PR #856.

**Comment by wisererik** [comment]
it has been fixed, will close it.
