### ISSUE TITLE
(backlog)Naming consistency between LVM metrics driver and exporter

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/opensds#746]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
The format of the metrics data received by Prometheus, is different for data coming from driver and being pushed to Prometheus vs. the data being scraped from the exporter

**What you expected to happen**:
The naming conventions for both data should be the same, so there is no difference when the data reaches Prometheus

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Already solved by #744 , please close this issue.

**Comment by rhsakarpos** [comment]
solved by #744, closing
