### ISSUE TITLE
(backlog)Disk metrics support

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/opensds#747]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
To collect disk metrics in the LVM driver

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NajmudheenCT** [comment]
https://github.com/opensds/opensds/pull/764 has the fix. Please close this ticket.
