### ISSUE TITLE
(backlog)Metrics interface type change to use storage type only

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/opensds#748]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
Change the POST API for collect metrics, to take the storage type as input, such as LVM, CEPH etc. 
For the given type, collect metrics for all the resource types and instances

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NajmudheenCT** [comment]
Code https://github.com/opensds/opensds/pull/764 merged ,Please close
