### ISSUE TITLE
Telemetry UI integration

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/opensds#754]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
Integrate the dashboard and the backend API for telemetry APIs. Includes the configuration file upload/download and GET API for re-direct URLs

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
I think it's already solved in dashboard, is that right?

**Comment by anvithks** [comment]
These APIs were added to the dashboard in following PRs in the dashboard repository.
[# 71](https://github.com/opensds/opensds-dashboard/pull/71)  
[# 68](https://github.com/opensds/opensds-dashboard/pull/68)  
[# 93](https://github.com/opensds/opensds-dashboard/pull/93)

**Comment by leonwanghui** [comment]
Will close this issue.
