### ISSUE TITLE
The HTTP Content-type header of REST-API response is not 'application/json'

### ISSUE THREAD

**Issue by hirokikmr** [opensds/opensds#756]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Hi. When I execute OpenSDS REST-API, the HTTP Content-type header of REST-API response is 'text/plain' as follows.
I think it should be 'application/json'.

```
# curl -X GET --noproxy localhost -s -vv -H 'Accept: application/json'  http://localhost:50040/v1beta/test/block/volumes/ | jq .
*   Trying ::1...
* Connected to localhost (::1) port 50040 (#0)
> GET /v1beta/test/block/volumes/ HTTP/1.1
> Host: localhost:50040
> User-Agent: curl/7.47.0
> Accept: application/json
>
< HTTP/1.1 200 OK
< Content-Length: 2
< Date: Mon, 20 May 2019 10:56:45 GMT
< Content-Type: text/plain; charset=utf-8
<
{ [2 bytes data]
* Connection #0 to host localhost left intact
[]
#`
```

**What you expected to happen**:
The HTTP Content-type header of REST-API response is 'application/json'.

**How to reproduce it (as minimally and precisely as possible)**:
You can reproduce by executing any REST-API.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: development branch (1a13191)
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wisererik** [comment]
@xxwjj please take a look at it

**Comment by leonwanghui** [comment]
@hirokikmr This issue has been fixed, please take a test : )

**Comment by leonwanghui** [comment]
Will close this issue for now, please reopen it if something still goes wrong.

**Comment by hirokikmr** [comment]
@leonwanghui  I'm sorry for late reply. I confirmed that it has been fixed. Thank you!
