### ISSUE TITLE
Add precheck when deleting profile

### ISSUE THREAD

**Issue by xxwjj** [opensds/opensds#758]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

testing steps:
1.create snapshot specified a profile.
2. delete the profile.
3. delete snapshot.

**What happened**:
Cann't delete the snapshot:
```
root@ubuntu:~# osdsctl volume snapshot delete e146752a-7f37-49a4-87b7-c8db18ad3db5
ERROR: delete snapshot failed: Wrong resource uuid provided!
```
logs:
```
I0520 22:40:14.772898   29116 accesslog.go:26] [D] 127.0.0.1:38032 -- DELETE /v1beta/e93b4c0934da416eb9c8d120c5d04d96/block/snapshots/e146752a-7f37-49a4-87b7-c8db18ad3db5
E0520 22:40:14.775123   29116 etcd.go:1364] When get profile in db:Wrong resource uuid provided!
E0520 22:40:14.775871   29116 base.go:95] delete snapshot failed: Wrong resource uuid provided!

```
**What you expected to happen**:

Check if the profile is used by others, if so ,return an error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
@xxwjj Could u pull a PR to resolve this bug?

**Comment by leonwanghui** [comment]
We can fix this issue in the Hotpot side, but I am wondering if it has impact on dashboard if we add pre-check before deleting profile.

**Comment by skdwriting** [comment]
@Shruthi-1MN , please keep the same error code and only append the error message, then the dashboard should be able to give the proper error message on delete profile error
