### ISSUE TITLE
Updates a volume attachments

### ISSUE THREAD

**Issue by hirokikmr** [opensds/opensds#790]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Update volume attachment REST-API can change 'hostInfo'.
However there is no storage driver function for updating volume attachment. Currently, it change the database value only.
If 'hostInfo.initiator' is specified in create volume attachment, the storage driver set it to the storage devise for access control. 
Therefore I think the storage driver function for updating volume attachment is necessary.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: development branch (1a13191)
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skdwriting** [comment]
@xxwjj  could you please reply to this issue?

**Comment by leonwanghui** [comment]
@hirokikmr Currently the UpdateVolumeAttachment method is only allowed to update the metadata of volume attachment, so there is no need to let storage driver implement that function. But one issue you mentioned about updating `HostInfo` (or `ConnectionInfo`) should not be allowed, and we need to resolve that.
