### ISSUE TITLE
Create file share fails because of no availability pool

### ISSUE THREAD

**Issue by Shruthi-1MN** [opensds/opensds#799]
**Is this a BUG REPORT or FEATURE REQUEST?**:
After adding nfs native driver pool capabilities, create file share is failing after this PR pool creation
https://github.com/opensds/opensds/pull/774

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Pull latest development branch code and install hotpot
Create file share cmd 
curl --header "Content-Type: application/json" --data '{"name":"fileshare1", "description":"file share test", "size":3 }' http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares

Throws following error in controller logic
I0531 13:49:29.576109    5613 controller.go:892] controller create fileshare:  get fileshare from db &{BaseModel:0xc000228780 TenantId:e93b4c0934da416eb9c8d120c5d04d96 UserId: Name:fileshare1 Protocols:[] Description:file share test Size:3 AvailabilityZone:default Status:creating PoolId: ProfileId:b4e6a5e9-62cd-4eb2-8552-ba59a1b1b228 SnapshotId: ExportLocations:[] Metadata:map[]}
E0531 13:49:29.583240    5613 filter.go:99] pool: opensds-files-default doesn't provide capability: extras.dataStorage.storageAccessCapability
E0531 13:49:29.583325    5613 selector.go:283] filter supported pools failed: no available pool to meet user's requirement

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Can u use `osdsctl` tool to try it?

**Comment by Shruthi-1MN** [comment]
Fixed in PR https://github.com/opensds/opensds/pull/801
