### ISSUE TITLE
Report 400 when creating a snapshot for file share

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#811]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:

When I was creating a snapshot for file share, the server report 400 and "no default profile". Actually, I didn't use default profile and I created a new profile.

**What you expected to happen**:

snapshot can be created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: v0.5.3
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
In the latest code, I didn't find the error, please have a check.
