### ISSUE TITLE
Dashboard is not showing Exportlocation and updatedAt in basic information

### ISSUE THREAD

**Issue by PravinRanjan10** [opensds/opensds#814]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Dashboard should show export location after creation of fileshare and updateAt after updation 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
@jimccfun

**Comment by skdwriting** [comment]
@jimccfun , sent invitation to join. please join. So i can assign the issue :)
