### ISSUE TITLE
Access and Delete issues in file share.

### ISSUE THREAD

**Issue by sfzeng** [opensds/opensds#817]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Item count is not correct when deleting file share. As below:
![item_count_error](https://user-images.githubusercontent.com/38932432/59030707-496e1800-8894-11e9-8a03-5142cccee29a.png)
**What you expected to happen**:
It should be 1 file, not 3 files.
**How to reproduce it (as minimally and precisely as possible)**:
Just choose some items to delete, it can be reproduced easily.

**What happened**:
When I choose one file share and delete it, I got the status in 'errorDeleting' for a long time, and it cannot be deleted anymore. As below:
![delete_error](https://user-images.githubusercontent.com/38932432/59030995-15dfbd80-8895-11e9-8186-3345c24e9ab4.png)
**What you expected to happen**:
I can be deleted successfully.
**How to reproduce it (as minimally and precisely as possible)**:
Create a file share, create some ACLs, and then delete it.

**What happened**:
Ip can work when creating ACL, but network segment does not work. As below:
![ACL_network_segement_error_1](https://user-images.githubusercontent.com/38932432/59031154-7c64db80-8895-11e9-9a48-f48793c57874.png)
![ACL_network_segement_error_2](https://user-images.githubusercontent.com/38932432/59031165-82f35300-8895-11e9-80ed-8acf6f9eb659.png)
**What you expected to happen**:
After created an ACL with network segment, I can see the exported path by run command of showmount or exportfs, and I can use this share path.
**How to reproduce it (as minimally and precisely as possible)**:
Use network segment to create ACL of a share path.

**What happened**:
Create ACL with only read permission, but still can write. As below:
![permission_error_1](https://user-images.githubusercontent.com/38932432/59031373-12006b00-8896-11e9-9298-e0d6353931fd.png)
![permission_error_2](https://user-images.githubusercontent.com/38932432/59031380-188ee280-8896-11e9-83fc-fc7e2549e33e.png)
**What you expected to happen**:
Can not write.
**How to reproduce it (as minimally and precisely as possible)**:
Create an ACL with read permission, then mount the file share and write to it.

**Environment**:
- Hotpot(release/branch) version: development branch
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools: manually
- Others:  dash-board: development branch

**Comment by jimccfun** [comment]
@sfzeng the first problem has been fixed, there is no such problem in the latest version.
