### ISSUE TITLE
Status of file share snapshot is always 'creating'

### ISSUE THREAD

**Issue by sfzeng** [opensds/opensds#818]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
I tried to create a snapshot of a file share, but its status is always in 'creating'. As below:
![snapshot_creating_error](https://user-images.githubusercontent.com/38932432/59031834-5cceb280-8897-11e9-8a05-3af80892beab.png)
**What you expected to happen**:
Snapshot can be created successfully, and its status is normal.
**How to reproduce it (as minimally and precisely as possible)**:
Choose a file to create snapshot,  and you can get it.

**Environment**:
- Hotpot(release/branch) version: development branch
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools: manually
- Others: NA

**Comment by PravinRanjan10** [comment]
![File_1](https://user-images.githubusercontent.com/41313813/59032662-d5e8ee00-8834-11e9-8c82-7cbb61c72b80.png)
![snap_1](https://user-images.githubusercontent.com/41313813/59032672-da150b80-8834-11e9-9207-c4a58060e48e.png)

**Comment by PravinRanjan10** [comment]
For my case, snapshot is creating successfully and status is available.  Can you give some more detail to reproduce your problem? or can you give log?

**Comment by sfzeng** [comment]
@PravinRanjan10 How to get the log?

**Comment by Shruthi-1MN** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST?**:
> 
> > /kind bug
> 
> **What happened**:
> I tried to create a snapshot of a file share, but its status is always in 'creating'. As below:
> ![snapshot_creating_error](https://user-images.githubusercontent.com/38932432/59031834-5cceb280-8897-11e9-8a05-3af80892beab.png)
> **What you expected to happen**:
> Snapshot can be created successfully, and its status is normal.
> **How to reproduce it (as minimally and precisely as possible)**:
> Choose a file to create snapshot, and you can get it.
> 
> **Environment**:
> 
> * Hotpot(release/branch) version: development branch
> * OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
> * Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
> * Install tools: manually
> * Others: NA

It is because of no pool capability match, you can check in osdslet.ERROR Log and osdsdock.ERROR log file.

**Comment by Shruthi-1MN** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST?**:
> 
> > /kind bug
> 
> **What happened**:
> I tried to create a snapshot of a file share, but its status is always in 'creating'. As below:
> ![snapshot_creating_error](https://user-images.githubusercontent.com/38932432/59031834-5cceb280-8897-11e9-8a05-3af80892beab.png)
> **What you expected to happen**:
> Snapshot can be created successfully, and its status is normal.
> **How to reproduce it (as minimally and precisely as possible)**:
> Choose a file to create snapshot, and you can get it.
> 
> **Environment**:
> 
> * Hotpot(release/branch) version: development branch
> * OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
> * Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
> * Install tools: manually
> * Others: NA

Wrong profile choosen that might be the reason of file share status 'creating' always

**Comment by PravinRanjan10** [comment]
This is working fine. Me and @sfzeng  discussed. I am closing this.

**Comment by skdwriting** [comment]
@PravinRanjan10 can we close it?

**Comment by sfzeng** [comment]
It's work now, can be closed.
