### ISSUE TITLE
File share name is empty is creates fileshare id and updates status as error

### ISSUE THREAD

**Issue by Shruthi-1MN** [opensds/opensds#831]
**Is this a BUG REPORT or FEATURE REQUEST?**:
```

root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds#   curl --header "Content-Type: application/json" --data   '{"name":"", "description":"file share   test2", "size":3 }' http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares
{"id":"c0d56198-30a9-4245-95df-b7a3ae61eacc","createdAt":"2019-06-07T15:26:53","updatedAt":"2019-06-07T15:26:53","tenantId":"e93b4c0934da416eb9c8d120c5d04d96","description":"file   share   test2","size":3,"availabilityZone":"default","status":"creating","profileId":"7721dbcc-679c-4be0-98d5-e100ebb35c90"}
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds#   curl -X GET   http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares/c0d56198-30a9-4245-95df-b7a3ae61eacc
{"id":"c0d56198-30a9-4245-95df-b7a3ae61eacc","createdAt":"2019-06-07T15:26:53","updatedAt":"2019-06-07T15:26:53","tenantId":"e93b4c0934da416eb9c8d120c5d04d96","description":"file   share   test2","size":3,"availabilityZone":"default","status":"error","profileId":"7721dbcc-679c-4be0-98d5-e100ebb35c90"}
```
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I tried to create file share of empty string, it is creating fileshare id and updates the status as error.

**What you expected to happen**:
It should through error for user when they input empty string. It should not create fileshare id with status as error. 

**How to reproduce it (as minimally and precisely as possible)**:
Install opensds, make sure all the process are running.
Create file share with empty string name. 
You will get a response body with fileshare id and status as error

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skdwriting** [comment]
@Shruthi-1MN , please add the issue description clearly. What happened and what is expected.

**Comment by Shruthi-1MN** [comment]
> @Shruthi-1MN , please add the issue description clearly. What happened and what is expected.

Updated clearly.

**Comment by PravinRanjan10** [comment]
@Shruthi-1MN  can you try with latest code. I have fixed that issue now. Thnaks

**Comment by Shruthi-1MN** [comment]
```
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# curl --header "Content-Type: application/json" --data '{"name":"", "description":"file share test", "size":3 }' http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares
{"code":400,"message":"create fileshare failed: Empty fileshare name is not allowed. Please give valid name."}
```
Working fine, so closing.
