### ISSUE TITLE
Create file share access client failed because of wrong access ability.

### ISSUE THREAD

**Issue by jackhaibo** [opensds/opensds#834]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When I try to create a file share access client, an error occurred:
```
build/out/bin/osdsctl fileshare acl create e4dbc4f8-3f35-4886-9818-5dc9fcdc04d2 -a 8.46.187.238  -c read -t ip --debug
DEBUG: 2019/06/10 19:59:24 fileshareacl.go:112: error parsing accessCapability read: invalid character 'r' looking for beginning of value
```

**What you expected to happen**:
I hope access ability should be `read` or `read,write`, the access client can be created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Use command `build/out/bin/osdsctl fileshare acl create e4dbc4f8-3f35-4886-9818-5dc9fcdc04d2 -a 8.46.187.238  -c read,write -t ip --debug` to reproduce this error.

**Anything else we need to know?**:
@BaiHuoYu please take a look at this issue.

**Environment**:
- Hotpot(release/branch) version: development
- OS (e.g. from /etc/os-release):ubuntu 16.04

**Comment by leonwanghui** [comment]
Related to #839

**Comment by BaiHuoYu** [comment]
Today I tested the latest code. Do you see if it is related to your problem?
osdsctl fileshare acl create 6bf19304-1038-460a-85d6-c76395b49bd9 -t ip -a "0.0.0.0/0" -c '["read","write"]'
+------------------+--------------------------------------+
| Property | Value |
+------------------+--------------------------------------+
| Id | 1ce1b768-bd2d-4666-b2f3-0cdcc9e3d998 |
| CreatedAt | 2019-06-12T10:20:51 |
| TenantId | e93b4c0934da416eb9c8d120c5d04d96 |
| FileShareId | 6bf19304-1038-460a-85d6-c76395b49bd9 |
| Type | ip |
| AccessCapability | [read write] |
| AccessTo | 0.0.0.0/0 |
| Description | |
+------------------+--------------------------------------+

**Comment by PravinRanjan10** [comment]
![acl](https://user-images.githubusercontent.com/41313813/59549853-4ef8eb80-8f81-11e9-84dd-e0ea7c5a821e.png)

**Comment by PravinRanjan10** [comment]
![acl1](https://user-images.githubusercontent.com/41313813/59549862-6c2dba00-8f81-11e9-9cf3-8614b5e20679.png)

**Comment by PravinRanjan10** [comment]
I tested with latest code. ACL is working fine

**Comment by skdwriting** [comment]
@jackhaibo , please check and confirm, we can close this.
