### ISSUE TITLE
[dashboard]Some problems about creating and updating fileshare

### ISSUE THREAD

**Issue by sfzeng** [opensds/opensds#836]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Create fileshare with a name has 128 characters failed while creating a file share with a name has 4 characters(other parameters the same) succeed. As below:
![128_erro1](https://user-images.githubusercontent.com/38932432/59202186-86a51380-8bce-11e9-93f6-3ec6183eb265.png)
![128_error2](https://user-images.githubusercontent.com/38932432/59202195-8e64b800-8bce-11e9-8d6e-06e0cd06001f.png)
**What you expected to happen**:
1. Create fileshare successfully.
2. Display correctly, the size and status are not covered by name.
**How to reproduce it (as minimally and precisely as possible)**:
Create a fileshare with the name has 128 characters, other parameters use the default value.

**What happened**:
When I tried to update fileshare, and set the new name to be an empty string,  I can click 'ok' but nothing changed.
**What you expected to happen**:
I cannot click 'ok'.
**How to reproduce it (as minimally and precisely as possible)**:
1. Choose a fileshare which status is available.
2. Choose 'More' > 'Modify' and set the name to be empty.
3. Click ok.

**What happened**:
I tried to create a fileshare, which size is more than pool size, it created successfully, but its status is error.
**What you expected to happen**:
Create failed.
**How to reproduce it (as minimally and precisely as possible)**:
Create a fileshare which size is more than the pool size.

**What happened**:
I tried to update the description of fileshare, but the description is not updated as expected. As below:
![update error1](https://user-images.githubusercontent.com/38932432/59206010-a04a5900-8bd6-11e9-88a1-058ac094e016.png)
![update description error2](https://user-images.githubusercontent.com/38932432/59206034-a9d3c100-8bd6-11e9-8096-576f511b879a.png)
**What you expected to happen**:
The description is updated.
**How to reproduce it (as minimally and precisely as possible)**:
Choose a fileshare which status is available and modify it's description to any string.

**Anything else we need to know?**: 
N/A

**Environment**:
- Hotpot(release/branch) version: development branch
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools: manually
- Others:  dash-board: development branch

**Comment by skdwriting** [comment]
Do we have any limitation on the fileshare name? please ensure this test is covered in our test case list

**Comment by PravinRanjan10** [comment]
@sfzeng It is working fine with latest code. Please verify.

**Comment by leonwanghui** [comment]
Already tested it.
