### ISSUE TITLE
Osdsctl not creating volume

### ISSUE THREAD

**Issue by NajmudheenCT** [opensds/opensds#868]
**Is this a BUG REPORT or FEATURE REQUEST?**:
When I create volume from CLI using below command I get 'ERROR' response
root@ubuntu:~#  osdsctl volume create 1 --name=test
ERROR:
root@ubuntu:~#
/kind bug

**What happened**:
Hope there is no default profile available, 
**What you expected to happen**:
volume should be created using default profile.
**How to reproduce it (as minimally and precisely as possible)**:
execute  
osdsctl volume create 1 --name=test
without user created profiles.

**Logs**
osdsapiserver
=============
I0614 15:21:15.527958  116108 accesslog.go:26] [D] 192.168.20.159:42462 -- GET /v1beta/94b280022d0c4401bcf3b0ea85870519/profiles
W0614 15:21:15.528504  116108 etcd.go:108] The parameter limit is not present,use default value instead:50
W0614 15:21:15.528510  116108 etcd.go:130] The parameter offset is not present,use default value instead:0
W0614 15:21:15.528513  116108 etcd.go:147] The parameter sortDir is not present,use default value instead:desc
W0614 15:21:15.528518  116108 etcd.go:165] The parameter sortKey is not present,use default value instead:ID
I0614 15:23:48.326477  116108 accesslog.go:26] [D] 192.168.20.159:42478 -- GET /v1beta/94b280022d0c4401bcf3b0ea85870519/pools?offset=0&limit=50&sortDir=desc&sortKey=id
I0614 15:24:09.952908  116108 accesslog.go:26] [D] 192.168.20.159:42488 -- POST /v1beta/94b280022d0c4401bcf3b0ea85870519/block/volumes
W0614 15:24:09.953070  116108 volume.go:70] Use default profile when user doesn't specify profile.
I0614 15:29:10.327826  116108 accesslog.go:26] [D] 192.168.20.159:42502 -- POST /v1beta/94b280022d0c4401bcf3b0ea85870519/block/volumes
W0614 15:29:10.328019  116108 volume.go:70] Use default profile when user doesn't specify profile

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NajmudheenCT** [comment]
@leonwanghui @skdwriting @xing-yang @wisererik 
User is not aware of creating profile , either we should have default profile or document this

**Comment by skdwriting** [comment]
Can we update the document and provide a sample profile? Or we can add a default profile?

**Comment by joseph-v** [comment]
Wiki already contain steps to create profile https://github.com/opensds/opensds/wiki/OpenSDS-Cluster-Installation-through-Ansible

**Comment by NajmudheenCT** [comment]
Thanks @joseph-v I missed to see this in wiki.
Probabaly in next release we can think about having a default profile
