### ISSUE TITLE
Creating a fileshare status is error, but looking at the database doesn't have such a fileshare

### ISSUE THREAD

**Issue by jimccfun** [opensds/opensds#885]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I created a fileshare and the staus is error. but looking at the database doesn't hvae such a fileshare.
![fileshare](https://user-images.githubusercontent.com/37950702/59595672-d339a300-9128-11e9-8da6-b2a40fb7a786.png)

**What you expected to happen**:
When the status of the fileshare created is error or the creation failed, the API needs to return the specific reason
**How to reproduce it (as minimally and precisely as possible)**:
Create as many fileshare as possible, and it is easy to have error fileshare

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:development branch
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools:manually
- Others: dashboard: development branch

**Comment by PravinRanjan10** [comment]
![share2](https://user-images.githubusercontent.com/41313813/59615520-44388500-9140-11e9-82bb-4a9b277e2463.png)

**Comment by skdwriting** [comment]
as per @PravinRanjan10 , the db shows the error entry also currently.
(actually, this should be removed in case of error!;)
@jimccfun , please check this. Then close the issue!
