### ISSUE TITLE
No IP validation while attaching volume

### ISSUE THREAD

**Issue by kumarashit** [opensds/opensds#914]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**: Used orchestration to provision volume. Provided invalid/non-compliant IP address (192.168.20) for attachment. Volume created, volume attachment resulted in success but there is not actual attachment happened.

**What you expected to happen**: Volume attachment failure should throw error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Capri/v0.5.5
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
I think it's already solved by #912, please have a check.

**Comment by kumarashit** [comment]
I had looked into the PR and it seems it is just taking care of empty IP but not validating IP4 in the format a.b.c.d.
@jackhaibo can comment better

**Comment by jackhaibo** [comment]
I have added a judgment on ipv4, please see #912 `contrib/drivers/lvm/targets/iscsi.go `line 97

**Comment by kumarashit** [comment]
@jackhaibo yes just saw that. So it seems it will fix the issue. Thanks for the fix

**Comment by kumarashit** [comment]
I will verify it and will close

**Comment by kumarashit** [comment]
Closing
