### ISSUE TITLE
Detach a volume from osdctl CLI doesn't update the Volume status

### ISSUE THREAD

**Issue by kumarashit** [opensds/opensds#915]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Used Orchestration to provision volume. Volume created and attached to host. Now went to use osdsctl volume attachment delete <attach_id> command to detach volume. Attachment list doesn't show the volume attached but volume list show it inUse. Due to this am not able to delete the volume.

root@ubuntu:~# osdsctl volume list
+--------------------------------------+--------+-------------+---------+------+--------+--------------------------------------+
| Id                                   | Name   | Description | GroupId | Size | Status | ProfileId                            |
+--------------------------------------+--------+-------------+---------+------+--------+--------------------------------------+
| d34b4dbd-0c72-4b37-b42a-106642955062 | --     |             |         | 1    | inUse  | 7aebb505-79f5-426f-bf98-956940700a5b |
| 99c5b7b9-d9f5-418e-9b9f-5ce3337f6c02 | ak_vol |             |         | 1    | inUse  | 7aebb505-79f5-426f-bf98-956940700a5b |
| 4a0c8fce-2a97-4640-b290-6d8bfa0923c0 | vol1   |             |         | 1    | inUse  | 7aebb505-79f5-426f-bf98-956940700a5b |
| 0ded313c-8fb7-4adb-bf71-057613e9f588 | vol1   |             |         | 1    | inUse  | 7aebb505-79f5-426f-bf98-956940700a5b |
| 06a95c84-b74a-428c-8eec-bb801799f481 | vol1   |             |         | 5    | inUse  | 7aebb505-79f5-426f-bf98-956940700a5b |
+--------------------------------------+--------+-------------+---------+------+--------+--------------------------------------+
root@ubuntu:~# osdsctl volume attachment list
+--------------------------------------+--------------------------------------+------------+-----------+----------------+
| Id                                   | VolumeId                             | Mountpoint | Status    | AccessProtocol |
+--------------------------------------+--------------------------------------+------------+-----------+----------------+
| a3bb20d4-9bbd-40ae-b028-675830575ae9 | 99c5b7b9-d9f5-418e-9b9f-5ce3337f6c02 |            | available |                |
| 37079286-878c-4272-beb0-f5c61c711cee | 4a0c8fce-2a97-4640-b290-6d8bfa0923c0 |            | available |                |
| 0fe4d4a6-eda4-45b3-8593-3f7f17f8c901 | 0ded313c-8fb7-4adb-bf71-057613e9f588 |            | available |                |
+--------------------------------------+--------------------------------------+------------+-----------+----------------+
root@ubuntu:~#

**What you expected to happen**: Volume detachment should have updated volume status and volume op is now allowed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Capri/v0.5.5
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by himanshuvar** [comment]
Closing it now. The issues is not reproduced with Daito release. Volume status is updated to "available" after volume attachment delete.
Here are the screenshots.
![14](https://user-images.githubusercontent.com/8712951/73641783-8ba35f80-4696-11ea-89cd-690c3401aae4.PNG)
![15](https://user-images.githubusercontent.com/8712951/73641784-8ba35f80-4696-11ea-87d8-072cac1b210f.PNG)
