### ISSUE TITLE
FileShare-DashBoard: While Creating Access, AccessLevel cant be selected first time

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds#926]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
1. Create File Share
2. Click Create Access button
3. Click dropdown of AccessLevel
4. Select ReadOnly or Read,Write
5. Selected one wont be selected 
6. Error - AccessLevel required will be displayed and the popup keep flickering (Shivering)
7. Now try selection .. It works
**What you expected to happen**:
On First Selection, should select the Selected Access Level
![FileShareDashBoard_FirstTimeSelectionOfAccesslevel](https://user-images.githubusercontent.com/48289385/60084641-8459c200-9755-11e9-8a48-6cc30175da66.PNG)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
@satya-gorli , It is Dashboard issue. Could please ask yueju to take a look. Can you please close the issue here and open the same issue in dashboard.

**Comment by satya-gorli** [comment]
Created in Dashboard: #164
