### ISSUE TITLE
DashBoard-FileShare: FileShare not creating all the rules given

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds#928]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
**What happened**:
1. Create File share and make sure its in Available state
2. Click---> Create Access
3. Provide inputs including IP
4. Click add Rule in same popup
5. Provide different IP
6. Repeat steps 5 and 6 for 21 times
7. Overall 21 rules to be created.. but only 16 Access rules are created
![FileShareDashBoard_ Access Not Creating all given rules_1](https://user-images.githubusercontent.com/48289385/60086692-3050dc80-9759-11e9-9e38-15436b86ef11.PNG)

![FileShareDashBoard_ Access Not Creating all given rules_2](https://user-images.githubusercontent.com/48289385/60086716-38a91780-9759-11e9-8f29-4388d4afe207.PNG)

**What you expected to happen**:
All the rules should be created
or if any reason for not creating remaining should be displayed to user
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
@satya-gorli , 
It's dashboard issue, One access post api call allows only one acl at a time to create  in backend. In dashboard they should not allow user to create more than acl at time for the same fileshare. So please close the issue here, open new one in dashboard.

**Comment by satya-gorli** [comment]
@anvithks , Plz check this issue

**Comment by jimccfun** [comment]
@Shruthi-1MN I think we can create more than one acl for the same fileshare. so if we should not allow user to create more than one acl for the same fileshare, can you tell me why?

**Comment by PravinRanjan10** [comment]
we can create more than one ACL for same fileshare. Problem is little different, at a time, only one API can be called for each ACL. So if user want to add  5 ACL at a time(for example), then dashboard should call 5 API internally. Then this issues will be resolved. More detail, we can discuss over call.

**Comment by PravinRanjan10** [comment]
This issue is fixed. Now dashboard not allowing to create multiple rule at the same time.
![defect5](https://user-images.githubusercontent.com/41313813/71620394-ca557e00-2bef-11ea-9d64-e64fc655e9f3.png)
