### ISSUE TITLE
Dashboard-FileShare: After Some Access rules creation, FileShare status becoming error from available

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds#930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
**What happened**:
1. Create File Share and ensure its status is Available
2. create Access Rules more than 10 ( either in same Popup or seperately)
3. No response in dashboard after clicking OK Button
4. In Browser Response, we can see 400 error : {"code":400,"message":"createFileshareAcldbentry failed: only the status of file share is available, the acl can be created"}
5. Click cancel of popu and go and refresh File share page. File share status changed to ERROR from Available 
**What you expected to happen**:
1. Should create all the rules
2. If error, specific error should display in UI instead of showing same page without any error
3. Respose error statement also ambigious.. should be simple and understandable
![FileShareDashBoard_After some rules creation, Fileshare becoming error](https://user-images.githubusercontent.com/48289385/60087474-b4f02a80-975a-11e9-9286-580439748239.PNG)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
@satya-gorli 
Could you please share osdsdock.ERROR log?

**Comment by satya-gorli** [comment]
plz give me this file path

**Comment by Shruthi-1MN** [comment]
@satya-gorli , i check log on the machine which you have shared me the log location is /var/log/opensds/osdsdock.ERROR . It shows all acl's creation at a time. Below is the log details shows all acl request sent to backend, this is not supported this same as "DashBoard-FileShare: FileShare not creating all the rules given #928 "

"[{"id":"035db8bb-41d8-4a51-88d6-d24f197dbb58","createdAt":"2019-06-25T14:30:35","updatedAt":"2019-06-25T14:30:35","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"8.8.8.8/8"},{"id":"0427e594-b378-4f87-8596-4c52bc03fb34","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"7.1.1.1/1"},{"id":"15ede3b9-22d2-46ed-a5e5-6af71bc9dda4","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"27cc6334-9ce2-4224-aaaf-2204fb5e11c2","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"3.1.1.1/1"},{"id":"29efb62e-e90d-4436-8335-d9f36a4dd245","createdAt":"2019-06-25T14:14:24","updatedAt":"2019-06-25T14:14:24","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"8.8.8.8/8"},{"id":"2ce08a91-456c-4efa-b61c-4c34617236e5","createdAt":"2019-06-25T14:30:35","updatedAt":"2019-06-25T14:30:35","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"8.8.8.8/8"},{"id":"362e21e4-8cdd-46ec-b0f3-187f4b66fd6d","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"3b24a3f1-aae5-48ce-87df-6a01034bd1af","createdAt":"2019-06-25T14:11:46","updatedAt":"2019-06-25T14:11:46","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"4.4.4.4/4"},{"id":"4348540c-b3dd-4564-a627-caa3cd3a50d9","createdAt":"2019-06-25T14:12:25","updatedAt":"2019-06-25T14:12:25","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"6.6.6.6/6"},{"id":"48bbb52d-af7b-4ff4-aec2-3f5f0df30583","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"11.1.1.1/1"},{"id":"588210a1-a097-415d-a755-daf0b40edcd2","createdAt":"2019-06-25T14:11:58","updatedAt":"2019-06-25T14:11:58","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"5.5.5.5/5"},{"id":"5e0d34c6-935a-4405-a754-25e58cc3500f","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"65388339-a1d4-4cc4-b21b-caaa954e64f7","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"9.1.1.1/1"},{"id":"6597651e-a25a-43f8-86c6-dddfcf99666a","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"1.1.1.1/1"},{"id":"6712a3dd-0d4c-4eef-896f-ba35e2ed52b1","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"15.1.1.1/1"},{"id":"697af9d5-b98c-45ff-8119-e1aa1609d7de","createdAt":"2019-06-25T13:59:16","updatedAt":"2019-06-25T13:59:16","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"192.168.0.25/31"},{"id":"6ca3b307-a2d4-4988-b33e-a41cf3591f83","createdAt":"2019-06-25T14:13:59","updatedAt":"2019-06-25T14:13:59","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"2.2.2.2/2"},{"id":"6d86ef1c-0bfd-47e2-8a8f-eec710577de7","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"6e3b6c6d-126d-450f-b326-16685a5b5303","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"6ed43526-9ebd-446e-b7e6-09ca95a3afce","createdAt":"2019-06-25T14:30:35","updatedAt":"2019-06-25T14:30:35","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"8.8.8.8/8"},{"id":"74b0c1e4-179b-44db-8a35-57a42dfd7ed8","createdAt":"2019-06-25T14:22:00","updatedAt":"2019-06-25T14:22:00","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read","Write"],"accessTo":"11.11.11.11/11"},{"id":"896bd934-7186-42b1-8b3e-3f9c02d2e8f7","createdAt":"2019-06-25T14:11:24","updatedAt":"2019-06-25T14:11:24","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read","Write"],"accessTo":"3.3.3.3/3"},{"id":"8fbfcdea-d45c-4b27-a8c5-1439d9ef157b","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"14.1.1.1/1"},{"id":"9f815be3-a7e1-4b4d-ba65-d8938f7aeb2d","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"8.1.1.1/1"},{"id":"ab4af415-a08a-43f1-8ff7-94c6b70d33a0","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"ad812707-b9c5-413b-977e-04fb64d42798","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"10.1.1.1/1"},{"id":"b0bd610c-e657-47eb-a863-703d0ef166d8","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"2.1.1.1/1"},{"id":"b3948b3e-880d-4156-892e-6c5a29bf0812","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"4.1.1.1/1"},{"id":"b73209bd-1751-4ddc-bce9-9195050906df","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"b94e42fe-f98c-4615-b1f4-b57db8e84982","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"5.1.1.1/1"},{"id":"bb6ad017-7379-4131-a5c7-a6c35024b614","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"c55a272d-3bea-4ef0-8eb2-e8ea62ac692d","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"6.1.1.1/1"},{"id":"c64c82b8-79b1-4e2d-95c2-2fc1e64afddc","createdAt":"2019-06-25T14:35:18","updatedAt":"2019-06-25T14:35:18","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"0cc8e9ea-5ef5-452d-a144-d4e05307341f","type":"ip","accessCapability":["Read"],"accessTo":"12.12.12.12/12"},{"id":"c98735cf-61ad-49d2-87f5-97ca706b51ff","createdAt":"2019-06-25T14:10:45","updatedAt":"2019-06-25T14:10:45","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read","Write"],"accessTo":"1.1.1.1/11"},{"id":"cacf0595-1d65-40ce-86f2-dc717b6f371f","createdAt":"2019-06-25T14:11:09","updatedAt":"2019-06-25T14:11:09","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"2.2.2.2/2"},{"id":"cb5333a8-f7f3-455b-8d70-01265cee3302","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"16.1.1.1/1"},{"id":"d231a46f-705c-454c-a5f1-533d74cc6966","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"12.1.1.1/1"},{"id":"d61d6099-a282-4c44-8fed-158032b95a86","createdAt":"2019-06-25T14:30:35","updatedAt":"2019-06-25T14:30:35","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"8.8.8.8/8"},{"id":"ef741954-e590-48e6-8a23-c8dd402c3ea2","createdAt":"2019-06-25T14:47:20","updatedAt":"2019-06-25T14:47:20","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"ad92d331-8ff0-4b25-9706-482b7bea2ec8","type":"ip","accessCapability":["Read"],"accessTo":"13.1.1.1/1"},{"id":"fff19e70-504c-4fee-a784-dfe0089b31af","createdAt":"2019-06-25T14:15:03","updatedAt":"2019-06-25T14:15:03","tenantId":"94b280022d0c4401bcf3b0ea85870519","fileshareId":"b2f044e8-9c2f-4dad-9073-a8d108596c9f","type":"ip","accessCapability":["Read"],"accessTo":"9.9.9.9/9"}]"

I check the machine status, i see there is problem with keystone,
all services are running but not able to take any user request
root@ubuntu-123:/var/log/opensds# export OPENSDS_AUTH_STRATEGY=keystone
root@ubuntu-123:/var/log/opensds# export OPENSDS_ENDPOINT=http://192.168.20.123:50040
root@ubuntu-123:/var/log/opensds# export OS_AUTH_URL=http://192.168.20.123/identity
root@ubuntu-123:/var/log/opensds# export OS_USERNAME=admin
root@ubuntu-123:/var/log/opensds# export OS_PASSWORD=opensds@123
root@ubuntu-123:/var/log/opensds# export OS_TENANT_NAME=admin
root@ubuntu-123:/var/log/opensds# export OS_PROJECT_NAME=admin
root@ubuntu-123:/var/log/opensds# export OS_USER_DOMAIN_ID=default
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds# osdsctl fileshare list
ERROR: Get http://192.168.20.123:50040/v1beta/94b280022d0c4401bcf3b0ea85870519/file/shares?offset=0&limit=50&sortDir=desc&sortKey=id: dial tcp 192.168.20.123:50040: connect: connection refused
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds#
root@ubuntu-123:/var/log/opensds# ps -ef |grep osds
root      15767  15047  0 12:30 pts/1    00:00:00 grep --color=auto osds
root      91142      1  0 Jun25 ?        00:00:26 bin/osdslet
root      91224      1  0 Jun25 ?        00:00:29 bin/osdsapiserver
root      96407      1  0 Jun25 ?        00:00:39 bin/osdsdock
root@ubuntu-123:/var/log/opensds# osdsctl volume list
ERROR: Get http://192.168.20.123:50040/v1beta/94b280022d0c4401bcf3b0ea85870519/block/volumes?limit=50&sortKey=id&offset=0&sortDir=desc: dial tcp 192.168.20.123:50040: connect: connection refused

In osdsapiserver.INFO log has these entries
W0625 14:09:57.723001   91224 etcd.go:165] The parameter sortKey is not present,use default value instead:ID
E0625 14:10:45.617286   91224 utils.go:111] verify token:Authentication failed, retry 1 time(s)
I0625 14:10:45.717651   91224 accesslog.go:26] ^[[32m[D] 127.0.0.1:47630 -- POST /v1beta/94b280022d0c4401bcf3b0ea85870519/file/acls^[[0m

Though all services are running there is keystone issue is there on your test bed, please resolve these.  
This is duplicate of this issue #928 .
So please close this issue.

**Comment by satya-gorli** [comment]
Plz show in any working environment.. If this issue not exists, then I can close
