### ISSUE TITLE
FileShare-DashBoard: Snapshot with duplicate names getting created

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds#931]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
**What happened**:
1. create File Share with state available
2. Create Snapshot for the created FileShare
3. Repeate step2 with the same name
4. Its allowing to create the snapshots with same name
**What you expected to happen**:
1. There is no point of creating snapshots with same name. should restrict
![FileShareDashBoard_ Snapshot creation allowing duplicate names](https://user-images.githubusercontent.com/48289385/60088656-a6a30e00-975c-11e9-81f2-17142a49f3a5.PNG)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
Issue has been fixed in PR  #936 , some test results are also added in PR #936.
