### ISSUE TITLE
Need to cherry pick commits merged to Development after Capri release into Master

### ISSUE THREAD

**Issue by xing-yang** [opensds/opensds#947]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
There are some PRs that got merged into Development branch after the Capri release.
They need to be cherry-picked into Master, otherwise they will be lost because Development branch is deprecated.

I have identified one PR that needs to be cherry-picked:
https://github.com/opensds/opensds/pull/937

@leonwanghui Can you check and make sure all PRs merged to Development after Capri release are cherry-picked into Master?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Solved by #952
