### ISSUE TITLE
Acl creation is not creating backend rule properly 

### ISSUE THREAD

**Issue by Shruthi-1MN** [opensds/opensds#950]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When first time i tried to create acl with "read" permission and second time with read and write permissions for the same ip. But i can't find both the rules on backend
opensds db entry is created but actual rule i didn't find filesystem
"exportfs -v"  has only one entry i.e second rule

**What you expected to happen**:
When we create 2 different acl rule for the same IP. It should create both rules on backend file system

**How to reproduce it (as minimally and precisely as possible)**:
First create file share
For that file share create 2  different acl rule for the same ip using cli/dashboard/curl command.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shruthi-1MN** [comment]
@PravinRanjan10, Please take a look at this issue

**Comment by PravinRanjan10** [comment]
For same IP, two rules not possible. This is not a valid scenario. Always 2nd rule will be updated if user have give same ip. This issue is sort of validation in dashboard/API(I mean two entries of rule must not be there for same IP)

**Comment by Shruthi-1MN** [comment]
@PravinRanjan10 , It it is so then fix the issue in apiserver itself.

**Comment by jimccfun** [comment]
@Shruthi-1MN @PravinRanjan10 I'm going to add restrictions in dashboard

**Comment by PravinRanjan10** [comment]
@jimccfun  what restriction you are going to add??

**Comment by Shruthi-1MN** [comment]
It is fixed in PR #1019, so closing this issue.

**Comment by wisererik** [comment]
it's not fixed, I reopen it

**Comment by PravinRanjan10** [comment]
It is fixed by this PR #1143
