### ISSUE TITLE
Fileshare: suggest adding ExportLocations in DeleteFileShareOpts

### ISSUE THREAD

**Issue by shuoranliu** [opensds/opensds#951]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There is no `ExportLocations` field in the `DeleteFileShareOpts` struct.

**What you expected to happen**:

Since `ExportLocations` is stored in the `FileShareSpec` when creating file share, I think it is better to add this filed in the `DeleteFileShareOpts` struct. In this way, drivers can do umount before deleting a file share.

**How to reproduce it (as minimally and precisely as possible)**:

I checked the  nfs file share driver, and found out that export location is hard-coded due to the lack of `ExportLocations` in `DeleteFileShareOpts`.

**Anything else we need to know?**:

No

**Environment**:

N/A

**Comment by leonwanghui** [comment]
@shuoranliu Thanks for pointing out this issue, do u want to pull a PR to resolve this? Or @PravinRanjan10 could u help address this issue?

**Comment by PravinRanjan10** [comment]
Agree with @shuoranliu. I will add export location in deletefileshareOpts.
