### ISSUE TITLE
Incorrect parameter in wiki

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/opensds#995]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
The chapter "Uninstall the local cluster" in wiki [OpenSDS-Local-Cluster-with-Multi-tenants-Installation](https://github.com/opensds/opensds/wiki/OpenSDS-Local-Cluster-with-Multi-tenants-Installation#opensdshotpot) has a incorrect parameter:
`cd $GOPATH/src/github.com/opensds/opensds && install/devsds/uninstall.sh -purge`
should be
`cd $GOPATH/src/github.com/opensds/opensds && install/devsds/uninstall.sh --purge`

**What you expected to happen**:
The parameter should be correct.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: latest
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools:
- Others:

**Comment by anvithks** [comment]
I have fixed this. @ThisIsClark you can see the changes in the document now.
