### ISSUE TITLE
Create file share failed because of no default named profile

### ISSUE THREAD

**Issue by Shruthi-1MN** [opensds/opensds#996]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Create file share failed to create file share through CLI
```
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# osdsctl fileshare create -n "lop1" 1
ERROR: get profile failed: can't find profile(name: default, storageType:file)
```
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Tried to create file share with default profile but got error as "can't find profile name default"
```
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# osdsctl fileshare create -n "sample1" 1
ERROR: get profile failed: can't find profile(name: default, storageType:file)
```
**What you expected to happen**:
It should create file share with default profile of storage type "file"

**How to reproduce it (as minimally and precisely as possible)**:
1) To install and set up environment follow the instruction in https://github.com/opensds/opensds/wiki/OpenSDS-Local-Cluster-with-Multi-tenants-Installation 
2) using osdsctl tool create file share as below
``` osdsctl fileshare create -n "sample1" 1 ```

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Did you check the profile list? Was the installation proper.
I just installed and checked and it worked fine.
root@aks:~/gopath/src/github.com/opensds/opensds# build/out/bin/osdsctl profile list
+--------------------------------------+---------+----------------+-------------+
| Id                                   | Name    | Description    | StorageType |
+--------------------------------------+---------+----------------+-------------+
| 98561deb-ab3d-4bf2-8594-3c65b078174b | default | default policy | file        |
| 04ad2188-45c3-4f37-ba70-d3efa9e73852 | default | default policy | block       |
+--------------------------------------+---------+----------------+-------------+
root@aks:~/gopath/src/github.com/opensds/opensds# osdsctl fileshare create -n "lop1" 1
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| Id               | e0c774b7-9460-4d5f-8e68-e97c8a5fb2e6 |
| CreatedAt        | 2019-08-28T17:07:15                  |
| TenantId         | 94b280022d0c4401bcf3b0ea85870519     |
| UserId           | 558057c4256545bd8a307c37464003c9     |
| Name             | lop1                                 |
| Protocols        | []                                   |
| Description      |                                      |
| Size             | 1                                    |
| AvailabilityZone | default                              |
| Status           | creating                             |
| PoolId           |                                      |
| ProfileId        | 98561deb-ab3d-4bf2-8594-3c65b078174b |
| SnapshotId       |                                      |
| ExportLocations  | []                                   |
| Metadata         | null                                 |
|                  |                                      |
+------------------+--------------------------------------+
root@aks:~/gopath/src/github.com/opensds/opensds# osdsctl fileshare list
+--------------------------------------+------+-----------+-------------+------+-----------+--------------------------------------+----------------------------+
| Id                                   | Name | Protocols | Description | Size | Status    | ProfileId                            | ExportLocations            |
+--------------------------------------+------+-----------+-------------+------+-----------+--------------------------------------+----------------------------+
| e0c774b7-9460-4d5f-8e68-e97c8a5fb2e6 | lop1 | [nfs]     |             | 1    | available | 98561deb-ab3d-4bf2-8594-3c65b078174b | [192.168.20.163:/var/lop1] |
+--------------------------------------+------+-----------+-------------+------+-----------+--------------------------------------+----------------------------+

**Comment by Shruthi-1MN** [comment]
> Did you check the profile list? Was the installation proper.
> I just installed and checked and it worked fine.

Did you check with latest master branch code?

**Comment by kumarashit** [comment]
You are Right.
This was the new code changes done. default_file/default_block should be the profile name we should use now. This has impact and we should analyze all places where this will affect

**Comment by wisererik** [comment]
@ThisIsClark  please have a look at it

**Comment by Shruthi-1MN** [comment]
It is working fine, so closing this issue as it has been fixed 
```
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# osdsctl profile list 
WARNING: OPENSDS_ENDPOINT is not specified, use default(http://localhost:50040)
WARNING: Not found Env OPENSDS_AUTH_STRATEGY, use default(noauth)
+--------------------------------------+---------------+------------------------------------------------+-------------+
| Id                                   | Name          | Description                                    | StorageType |
+--------------------------------------+---------------+------------------------------------------------+-------------+
| c92dd59a-186f-4f26-9134-87a4eefd4717 | default_file  | default policy                                 | file        |
| ac2f222a-9dc3-40d2-973f-3a4fb2a96bdb | default_block | default policy                                 | block       |
| 7815b342-9eb0-4781-8a03-32b4b20f28c3 | policy        | This is just to test all file share test cases | file        |
| 6b04349c-8908-4287-9b54-cf5491dc4594 | default_file1 | This is just to test all file share test cases | file        |
| 41412c87-9285-4379-8078-392de709abeb | default_file2 | default policy                                 | file        |
| 04f46c79-9498-4d29-a4d3-7996386723cc | default1      | This is just to test all file share test cases | file        |
+--------------------------------------+---------------+------------------------------------------------+-------------+
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# 
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# 
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# 
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# osdsctl fileshare create -n "kl1" 1 
WARNING: OPENSDS_ENDPOINT is not specified, use default(http://localhost:50040)
WARNING: Not found Env OPENSDS_AUTH_STRATEGY, use default(noauth)
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| Id               | 843b70d5-01da-4e6f-97f9-3a77ea0f83dc |
| CreatedAt        | 2019-10-03T12:31:25                  |
| TenantId         | e93b4c0934da416eb9c8d120c5d04d96     |
| UserId           |                                      |
| Name             | kl1                                  |
| Protocols        | []                                   |
| Description      |                                      |
| Size             | 1                                    |
| AvailabilityZone | default                              |
| Status           | creating                             |
| PoolId           |                                      |
| ProfileId        | c92dd59a-186f-4f26-9134-87a4eefd4717 |
| SnapshotId       |                                      |
| ExportLocations  | []                                   |
| Metadata         | null                                 |
|                  |                                      |
+------------------+--------------------------------------+
```
